#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAPI.DATA.TicketLE
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="LETicket")]
	public partial class TicketLEDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertMAS_APPROVE(MAS_APPROVE instance);
    partial void UpdateMAS_APPROVE(MAS_APPROVE instance);
    partial void DeleteMAS_APPROVE(MAS_APPROVE instance);
    partial void InsertMAS_DOC(MAS_DOC instance);
    partial void UpdateMAS_DOC(MAS_DOC instance);
    partial void DeleteMAS_DOC(MAS_DOC instance);
    partial void InsertMAS_SS(MAS_SS instance);
    partial void UpdateMAS_SS(MAS_SS instance);
    partial void DeleteMAS_SS(MAS_SS instance);
    partial void InsertTASK_MAIN(TASK_MAIN instance);
    partial void UpdateTASK_MAIN(TASK_MAIN instance);
    partial void DeleteTASK_MAIN(TASK_MAIN instance);
    partial void InsertTASK_SUB(TASK_SUB instance);
    partial void UpdateTASK_SUB(TASK_SUB instance);
    partial void DeleteTASK_SUB(TASK_SUB instance);
    #endregion
		
		public TicketLEDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["LETicketConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public TicketLEDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public TicketLEDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public TicketLEDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public TicketLEDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<MAS_APPROVE> MAS_APPROVEs
		{
			get
			{
				return this.GetTable<MAS_APPROVE>();
			}
		}
		
		public System.Data.Linq.Table<MAS_DOC> MAS_DOCs
		{
			get
			{
				return this.GetTable<MAS_DOC>();
			}
		}
		
		public System.Data.Linq.Table<MAS_SS> MAS_SSes
		{
			get
			{
				return this.GetTable<MAS_SS>();
			}
		}
		
		public System.Data.Linq.Table<TASK_MAIN> TASK_MAINs
		{
			get
			{
				return this.GetTable<TASK_MAIN>();
			}
		}
		
		public System.Data.Linq.Table<TASK_SUB> TASK_SUBs
		{
			get
			{
				return this.GetTable<TASK_SUB>();
			}
		}
		
		public System.Data.Linq.Table<VW_TICKET> VW_TICKETs
		{
			get
			{
				return this.GetTable<VW_TICKET>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.MAS_APPROVE")]
	public partial class MAS_APPROVE : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _APPROVE_ID;
		
		private string _APPROVE_NAME;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnAPPROVE_IDChanging(int value);
    partial void OnAPPROVE_IDChanged();
    partial void OnAPPROVE_NAMEChanging(string value);
    partial void OnAPPROVE_NAMEChanged();
    #endregion
		
		public MAS_APPROVE()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_APPROVE_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int APPROVE_ID
		{
			get
			{
				return this._APPROVE_ID;
			}
			set
			{
				if ((this._APPROVE_ID != value))
				{
					this.OnAPPROVE_IDChanging(value);
					this.SendPropertyChanging();
					this._APPROVE_ID = value;
					this.SendPropertyChanged("APPROVE_ID");
					this.OnAPPROVE_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_APPROVE_NAME", DbType="VarChar(50)")]
		public string APPROVE_NAME
		{
			get
			{
				return this._APPROVE_NAME;
			}
			set
			{
				if ((this._APPROVE_NAME != value))
				{
					this.OnAPPROVE_NAMEChanging(value);
					this.SendPropertyChanging();
					this._APPROVE_NAME = value;
					this.SendPropertyChanged("APPROVE_NAME");
					this.OnAPPROVE_NAMEChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.MAS_DOC")]
	public partial class MAS_DOC : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _DOC_ID;
		
		private string _DOC_NAME;
		
		private string _TYPE;
		
		private string _FLAG;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnDOC_IDChanging(int value);
    partial void OnDOC_IDChanged();
    partial void OnDOC_NAMEChanging(string value);
    partial void OnDOC_NAMEChanged();
    partial void OnTYPEChanging(string value);
    partial void OnTYPEChanged();
    partial void OnFLAGChanging(string value);
    partial void OnFLAGChanged();
    #endregion
		
		public MAS_DOC()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DOC_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int DOC_ID
		{
			get
			{
				return this._DOC_ID;
			}
			set
			{
				if ((this._DOC_ID != value))
				{
					this.OnDOC_IDChanging(value);
					this.SendPropertyChanging();
					this._DOC_ID = value;
					this.SendPropertyChanged("DOC_ID");
					this.OnDOC_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DOC_NAME", DbType="VarChar(100)")]
		public string DOC_NAME
		{
			get
			{
				return this._DOC_NAME;
			}
			set
			{
				if ((this._DOC_NAME != value))
				{
					this.OnDOC_NAMEChanging(value);
					this.SendPropertyChanging();
					this._DOC_NAME = value;
					this.SendPropertyChanged("DOC_NAME");
					this.OnDOC_NAMEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TYPE", DbType="VarChar(1)")]
		public string TYPE
		{
			get
			{
				return this._TYPE;
			}
			set
			{
				if ((this._TYPE != value))
				{
					this.OnTYPEChanging(value);
					this.SendPropertyChanging();
					this._TYPE = value;
					this.SendPropertyChanged("TYPE");
					this.OnTYPEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FLAG", DbType="VarChar(1)")]
		public string FLAG
		{
			get
			{
				return this._FLAG;
			}
			set
			{
				if ((this._FLAG != value))
				{
					this.OnFLAGChanging(value);
					this.SendPropertyChanging();
					this._FLAG = value;
					this.SendPropertyChanged("FLAG");
					this.OnFLAGChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.MAS_SS")]
	public partial class MAS_SS : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _SS_ID;
		
		private string _SS_NAME;
		
		private string _FLAG;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnSS_IDChanging(int value);
    partial void OnSS_IDChanged();
    partial void OnSS_NAMEChanging(string value);
    partial void OnSS_NAMEChanged();
    partial void OnFLAGChanging(string value);
    partial void OnFLAGChanged();
    #endregion
		
		public MAS_SS()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SS_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int SS_ID
		{
			get
			{
				return this._SS_ID;
			}
			set
			{
				if ((this._SS_ID != value))
				{
					this.OnSS_IDChanging(value);
					this.SendPropertyChanging();
					this._SS_ID = value;
					this.SendPropertyChanged("SS_ID");
					this.OnSS_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SS_NAME", DbType="VarChar(30)")]
		public string SS_NAME
		{
			get
			{
				return this._SS_NAME;
			}
			set
			{
				if ((this._SS_NAME != value))
				{
					this.OnSS_NAMEChanging(value);
					this.SendPropertyChanging();
					this._SS_NAME = value;
					this.SendPropertyChanged("SS_NAME");
					this.OnSS_NAMEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FLAG", DbType="VarChar(1)")]
		public string FLAG
		{
			get
			{
				return this._FLAG;
			}
			set
			{
				if ((this._FLAG != value))
				{
					this.OnFLAGChanging(value);
					this.SendPropertyChanging();
					this._FLAG = value;
					this.SendPropertyChanged("FLAG");
					this.OnFLAGChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TASK_MAIN")]
	public partial class TASK_MAIN : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private string _TICKETNO;
		
		private string _DETEIL;
		
		private System.Nullable<System.DateTime> _WORKDATE;
		
		private string _STCODE;
		
		private string _STATUS;
		
		private string _FLAG;
		
		private string _HDEP_NAME;
		
		private System.Nullable<System.DateTime> _HDEP_DATE;
		
		private string _RECEIVE_NAME;
		
		private System.Nullable<System.DateTime> _RECEIVE_DATE;
		
		private string _CLOSE_NAME;
		
		private System.Nullable<System.DateTime> _CLOSE_DATE;
		
		private System.Nullable<int> _APPROVE_ID;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnTICKETNOChanging(string value);
    partial void OnTICKETNOChanged();
    partial void OnDETEILChanging(string value);
    partial void OnDETEILChanged();
    partial void OnWORKDATEChanging(System.Nullable<System.DateTime> value);
    partial void OnWORKDATEChanged();
    partial void OnSTCODEChanging(string value);
    partial void OnSTCODEChanged();
    partial void OnSTATUSChanging(string value);
    partial void OnSTATUSChanged();
    partial void OnFLAGChanging(string value);
    partial void OnFLAGChanged();
    partial void OnHDEP_NAMEChanging(string value);
    partial void OnHDEP_NAMEChanged();
    partial void OnHDEP_DATEChanging(System.Nullable<System.DateTime> value);
    partial void OnHDEP_DATEChanged();
    partial void OnRECEIVE_NAMEChanging(string value);
    partial void OnRECEIVE_NAMEChanged();
    partial void OnRECEIVE_DATEChanging(System.Nullable<System.DateTime> value);
    partial void OnRECEIVE_DATEChanged();
    partial void OnCLOSE_NAMEChanging(string value);
    partial void OnCLOSE_NAMEChanged();
    partial void OnCLOSE_DATEChanging(System.Nullable<System.DateTime> value);
    partial void OnCLOSE_DATEChanged();
    partial void OnAPPROVE_IDChanging(System.Nullable<int> value);
    partial void OnAPPROVE_IDChanged();
    #endregion
		
		public TASK_MAIN()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TICKETNO", DbType="VarChar(20)")]
		public string TICKETNO
		{
			get
			{
				return this._TICKETNO;
			}
			set
			{
				if ((this._TICKETNO != value))
				{
					this.OnTICKETNOChanging(value);
					this.SendPropertyChanging();
					this._TICKETNO = value;
					this.SendPropertyChanged("TICKETNO");
					this.OnTICKETNOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DETEIL", DbType="VarChar(100)")]
		public string DETEIL
		{
			get
			{
				return this._DETEIL;
			}
			set
			{
				if ((this._DETEIL != value))
				{
					this.OnDETEILChanging(value);
					this.SendPropertyChanging();
					this._DETEIL = value;
					this.SendPropertyChanged("DETEIL");
					this.OnDETEILChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_WORKDATE", DbType="DateTime")]
		public System.Nullable<System.DateTime> WORKDATE
		{
			get
			{
				return this._WORKDATE;
			}
			set
			{
				if ((this._WORKDATE != value))
				{
					this.OnWORKDATEChanging(value);
					this.SendPropertyChanging();
					this._WORKDATE = value;
					this.SendPropertyChanged("WORKDATE");
					this.OnWORKDATEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_STCODE", DbType="VarChar(5)")]
		public string STCODE
		{
			get
			{
				return this._STCODE;
			}
			set
			{
				if ((this._STCODE != value))
				{
					this.OnSTCODEChanging(value);
					this.SendPropertyChanging();
					this._STCODE = value;
					this.SendPropertyChanged("STCODE");
					this.OnSTCODEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_STATUS", DbType="VarChar(1)")]
		public string STATUS
		{
			get
			{
				return this._STATUS;
			}
			set
			{
				if ((this._STATUS != value))
				{
					this.OnSTATUSChanging(value);
					this.SendPropertyChanging();
					this._STATUS = value;
					this.SendPropertyChanged("STATUS");
					this.OnSTATUSChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FLAG", DbType="VarChar(1)")]
		public string FLAG
		{
			get
			{
				return this._FLAG;
			}
			set
			{
				if ((this._FLAG != value))
				{
					this.OnFLAGChanging(value);
					this.SendPropertyChanging();
					this._FLAG = value;
					this.SendPropertyChanged("FLAG");
					this.OnFLAGChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HDEP_NAME", DbType="VarChar(50)")]
		public string HDEP_NAME
		{
			get
			{
				return this._HDEP_NAME;
			}
			set
			{
				if ((this._HDEP_NAME != value))
				{
					this.OnHDEP_NAMEChanging(value);
					this.SendPropertyChanging();
					this._HDEP_NAME = value;
					this.SendPropertyChanged("HDEP_NAME");
					this.OnHDEP_NAMEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HDEP_DATE", DbType="DateTime")]
		public System.Nullable<System.DateTime> HDEP_DATE
		{
			get
			{
				return this._HDEP_DATE;
			}
			set
			{
				if ((this._HDEP_DATE != value))
				{
					this.OnHDEP_DATEChanging(value);
					this.SendPropertyChanging();
					this._HDEP_DATE = value;
					this.SendPropertyChanged("HDEP_DATE");
					this.OnHDEP_DATEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RECEIVE_NAME", DbType="VarChar(50)")]
		public string RECEIVE_NAME
		{
			get
			{
				return this._RECEIVE_NAME;
			}
			set
			{
				if ((this._RECEIVE_NAME != value))
				{
					this.OnRECEIVE_NAMEChanging(value);
					this.SendPropertyChanging();
					this._RECEIVE_NAME = value;
					this.SendPropertyChanged("RECEIVE_NAME");
					this.OnRECEIVE_NAMEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RECEIVE_DATE", DbType="DateTime")]
		public System.Nullable<System.DateTime> RECEIVE_DATE
		{
			get
			{
				return this._RECEIVE_DATE;
			}
			set
			{
				if ((this._RECEIVE_DATE != value))
				{
					this.OnRECEIVE_DATEChanging(value);
					this.SendPropertyChanging();
					this._RECEIVE_DATE = value;
					this.SendPropertyChanged("RECEIVE_DATE");
					this.OnRECEIVE_DATEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CLOSE_NAME", DbType="VarChar(50)")]
		public string CLOSE_NAME
		{
			get
			{
				return this._CLOSE_NAME;
			}
			set
			{
				if ((this._CLOSE_NAME != value))
				{
					this.OnCLOSE_NAMEChanging(value);
					this.SendPropertyChanging();
					this._CLOSE_NAME = value;
					this.SendPropertyChanged("CLOSE_NAME");
					this.OnCLOSE_NAMEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CLOSE_DATE", DbType="DateTime")]
		public System.Nullable<System.DateTime> CLOSE_DATE
		{
			get
			{
				return this._CLOSE_DATE;
			}
			set
			{
				if ((this._CLOSE_DATE != value))
				{
					this.OnCLOSE_DATEChanging(value);
					this.SendPropertyChanging();
					this._CLOSE_DATE = value;
					this.SendPropertyChanged("CLOSE_DATE");
					this.OnCLOSE_DATEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_APPROVE_ID", DbType="Int")]
		public System.Nullable<int> APPROVE_ID
		{
			get
			{
				return this._APPROVE_ID;
			}
			set
			{
				if ((this._APPROVE_ID != value))
				{
					this.OnAPPROVE_IDChanging(value);
					this.SendPropertyChanging();
					this._APPROVE_ID = value;
					this.SendPropertyChanged("APPROVE_ID");
					this.OnAPPROVE_IDChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TASK_SUB")]
	public partial class TASK_SUB : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _LE_ID;
		
		private int _DOC_ID;
		
		private string _DETEIL_SUB;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnLE_IDChanging(int value);
    partial void OnLE_IDChanged();
    partial void OnDOC_IDChanging(int value);
    partial void OnDOC_IDChanged();
    partial void OnDETEIL_SUBChanging(string value);
    partial void OnDETEIL_SUBChanged();
    #endregion
		
		public TASK_SUB()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LE_ID", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int LE_ID
		{
			get
			{
				return this._LE_ID;
			}
			set
			{
				if ((this._LE_ID != value))
				{
					this.OnLE_IDChanging(value);
					this.SendPropertyChanging();
					this._LE_ID = value;
					this.SendPropertyChanged("LE_ID");
					this.OnLE_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DOC_ID", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int DOC_ID
		{
			get
			{
				return this._DOC_ID;
			}
			set
			{
				if ((this._DOC_ID != value))
				{
					this.OnDOC_IDChanging(value);
					this.SendPropertyChanging();
					this._DOC_ID = value;
					this.SendPropertyChanged("DOC_ID");
					this.OnDOC_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DETEIL_SUB", DbType="VarChar(50)")]
		public string DETEIL_SUB
		{
			get
			{
				return this._DETEIL_SUB;
			}
			set
			{
				if ((this._DETEIL_SUB != value))
				{
					this.OnDETEIL_SUBChanging(value);
					this.SendPropertyChanging();
					this._DETEIL_SUB = value;
					this.SendPropertyChanged("DETEIL_SUB");
					this.OnDETEIL_SUBChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.VW_TICKET")]
	public partial class VW_TICKET
	{
		
		private int _ID;
		
		private string _TICKETNO;
		
		private string _DETEIL;
		
		private System.Nullable<System.DateTime> _WORKDATE;
		
		private string _STCODE;
		
		private string _FNAME;
		
		private string _LNAME;
		
		private string _NICKNAME;
		
		private string _DPCODE;
		
		private string _SS_NAME;
		
		private string _STATUS;
		
		private string _FLAG;
		
		private string _APPROVE_NAME;
		
		private string _HDEP_NAME;
		
		private System.Nullable<System.DateTime> _HDEP_DATE;
		
		private string _RECEIVE_NAME;
		
		private System.Nullable<System.DateTime> _RECEIVE_DATE;
		
		private string _CLOSE_NAME;
		
		private System.Nullable<System.DateTime> _CLOSE_DATE;
		
		private System.Nullable<int> _APPROVE_ID;
		
		public VW_TICKET()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="Int NOT NULL")]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this._ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TICKETNO", DbType="VarChar(20)")]
		public string TICKETNO
		{
			get
			{
				return this._TICKETNO;
			}
			set
			{
				if ((this._TICKETNO != value))
				{
					this._TICKETNO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DETEIL", DbType="VarChar(100)")]
		public string DETEIL
		{
			get
			{
				return this._DETEIL;
			}
			set
			{
				if ((this._DETEIL != value))
				{
					this._DETEIL = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_WORKDATE", DbType="DateTime")]
		public System.Nullable<System.DateTime> WORKDATE
		{
			get
			{
				return this._WORKDATE;
			}
			set
			{
				if ((this._WORKDATE != value))
				{
					this._WORKDATE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_STCODE", DbType="VarChar(5)")]
		public string STCODE
		{
			get
			{
				return this._STCODE;
			}
			set
			{
				if ((this._STCODE != value))
				{
					this._STCODE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FNAME", DbType="VarChar(50)")]
		public string FNAME
		{
			get
			{
				return this._FNAME;
			}
			set
			{
				if ((this._FNAME != value))
				{
					this._FNAME = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LNAME", DbType="VarChar(50)")]
		public string LNAME
		{
			get
			{
				return this._LNAME;
			}
			set
			{
				if ((this._LNAME != value))
				{
					this._LNAME = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NICKNAME", DbType="VarChar(50)")]
		public string NICKNAME
		{
			get
			{
				return this._NICKNAME;
			}
			set
			{
				if ((this._NICKNAME != value))
				{
					this._NICKNAME = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DPCODE", DbType="NVarChar(10)")]
		public string DPCODE
		{
			get
			{
				return this._DPCODE;
			}
			set
			{
				if ((this._DPCODE != value))
				{
					this._DPCODE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SS_NAME", DbType="VarChar(30)")]
		public string SS_NAME
		{
			get
			{
				return this._SS_NAME;
			}
			set
			{
				if ((this._SS_NAME != value))
				{
					this._SS_NAME = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_STATUS", DbType="VarChar(1)")]
		public string STATUS
		{
			get
			{
				return this._STATUS;
			}
			set
			{
				if ((this._STATUS != value))
				{
					this._STATUS = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FLAG", DbType="VarChar(1)")]
		public string FLAG
		{
			get
			{
				return this._FLAG;
			}
			set
			{
				if ((this._FLAG != value))
				{
					this._FLAG = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_APPROVE_NAME", DbType="VarChar(50)")]
		public string APPROVE_NAME
		{
			get
			{
				return this._APPROVE_NAME;
			}
			set
			{
				if ((this._APPROVE_NAME != value))
				{
					this._APPROVE_NAME = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HDEP_NAME", DbType="VarChar(50)")]
		public string HDEP_NAME
		{
			get
			{
				return this._HDEP_NAME;
			}
			set
			{
				if ((this._HDEP_NAME != value))
				{
					this._HDEP_NAME = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HDEP_DATE", DbType="DateTime")]
		public System.Nullable<System.DateTime> HDEP_DATE
		{
			get
			{
				return this._HDEP_DATE;
			}
			set
			{
				if ((this._HDEP_DATE != value))
				{
					this._HDEP_DATE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RECEIVE_NAME", DbType="VarChar(50)")]
		public string RECEIVE_NAME
		{
			get
			{
				return this._RECEIVE_NAME;
			}
			set
			{
				if ((this._RECEIVE_NAME != value))
				{
					this._RECEIVE_NAME = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RECEIVE_DATE", DbType="DateTime")]
		public System.Nullable<System.DateTime> RECEIVE_DATE
		{
			get
			{
				return this._RECEIVE_DATE;
			}
			set
			{
				if ((this._RECEIVE_DATE != value))
				{
					this._RECEIVE_DATE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CLOSE_NAME", DbType="VarChar(50)")]
		public string CLOSE_NAME
		{
			get
			{
				return this._CLOSE_NAME;
			}
			set
			{
				if ((this._CLOSE_NAME != value))
				{
					this._CLOSE_NAME = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CLOSE_DATE", DbType="DateTime")]
		public System.Nullable<System.DateTime> CLOSE_DATE
		{
			get
			{
				return this._CLOSE_DATE;
			}
			set
			{
				if ((this._CLOSE_DATE != value))
				{
					this._CLOSE_DATE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_APPROVE_ID", DbType="Int")]
		public System.Nullable<int> APPROVE_ID
		{
			get
			{
				return this._APPROVE_ID;
			}
			set
			{
				if ((this._APPROVE_ID != value))
				{
					this._APPROVE_ID = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
