#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAPI.DATA.Hr_Register
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="HR-Register")]
	public partial class Hr_RegisterDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertSTEP_ONE(STEP_ONE instance);
    partial void UpdateSTEP_ONE(STEP_ONE instance);
    partial void DeleteSTEP_ONE(STEP_ONE instance);
    partial void InsertSTEP_TWO(STEP_TWO instance);
    partial void UpdateSTEP_TWO(STEP_TWO instance);
    partial void DeleteSTEP_TWO(STEP_TWO instance);
    partial void InsertSTEP_THREE_DETAIL(STEP_THREE_DETAIL instance);
    partial void UpdateSTEP_THREE_DETAIL(STEP_THREE_DETAIL instance);
    partial void DeleteSTEP_THREE_DETAIL(STEP_THREE_DETAIL instance);
    #endregion
		
		public Hr_RegisterDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["HR_RegisterConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public Hr_RegisterDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public Hr_RegisterDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public Hr_RegisterDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public Hr_RegisterDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<STEP_ONE> STEP_ONEs
		{
			get
			{
				return this.GetTable<STEP_ONE>();
			}
		}
		
		public System.Data.Linq.Table<STEP_TWO> STEP_TWOs
		{
			get
			{
				return this.GetTable<STEP_TWO>();
			}
		}
		
		public System.Data.Linq.Table<STEP_THREE_DETAIL> STEP_THREE_DETAILs
		{
			get
			{
				return this.GetTable<STEP_THREE_DETAIL>();
			}
		}
		
		public System.Data.Linq.Table<STEP_THREE_EDUCTION> STEP_THREE_EDUCTIONs
		{
			get
			{
				return this.GetTable<STEP_THREE_EDUCTION>();
			}
		}
		
		public System.Data.Linq.Table<STEP_THREE_EMPLOYMENT> STEP_THREE_EMPLOYMENTs
		{
			get
			{
				return this.GetTable<STEP_THREE_EMPLOYMENT>();
			}
		}
		
		public System.Data.Linq.Table<STEP_THREE_LANGUAGE> STEP_THREE_LANGUAGEs
		{
			get
			{
				return this.GetTable<STEP_THREE_LANGUAGE>();
			}
		}
		
		public System.Data.Linq.Table<STEP_THREE_TRAINING> STEP_THREE_TRAININGs
		{
			get
			{
				return this.GetTable<STEP_THREE_TRAINING>();
			}
		}
		
		public System.Data.Linq.Table<STEP_FOUR> STEP_FOURs
		{
			get
			{
				return this.GetTable<STEP_FOUR>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.STEP_ONE")]
	public partial class STEP_ONE : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _USERNO;
		
		private string _POSITION;
		
		private string _FULLNAME_TH;
		
		private string _NICKNAME_TH;
		
		private string _FULLNAME_EN;
		
		private string _NICKNAME_EN;
		
		private string _PEOPLEID;
		
		private string _ZONE;
		
		private string _PROVINCE_BIRTH;
		
		private System.Nullable<System.DateTime> _BIRTHDATE;
		
		private System.Nullable<int> _AGE;
		
		private System.Nullable<int> _WEIGHT;
		
		private System.Nullable<int> _HEIGHT;
		
		private string _ADDR_ROW1;
		
		private string _ADDR_ROW2;
		
		private string _ADDR_ROW3;
		
		private string _ADDR_HOME1;
		
		private string _ADDR_HOME2;
		
		private string _ADDR_HOME3;
		
		private string _ADDR_TEL;
		
		private string _ADDR_MOBILE;
		
		private string _ADDR_EMAIL;
		
		private string _ADDR_PHOTO;
		
		private System.Nullable<int> _FLAG;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnUSERNOChanging(string value);
    partial void OnUSERNOChanged();
    partial void OnPOSITIONChanging(string value);
    partial void OnPOSITIONChanged();
    partial void OnFULLNAME_THChanging(string value);
    partial void OnFULLNAME_THChanged();
    partial void OnNICKNAME_THChanging(string value);
    partial void OnNICKNAME_THChanged();
    partial void OnFULLNAME_ENChanging(string value);
    partial void OnFULLNAME_ENChanged();
    partial void OnNICKNAME_ENChanging(string value);
    partial void OnNICKNAME_ENChanged();
    partial void OnPEOPLEIDChanging(string value);
    partial void OnPEOPLEIDChanged();
    partial void OnZONEChanging(string value);
    partial void OnZONEChanged();
    partial void OnPROVINCE_BIRTHChanging(string value);
    partial void OnPROVINCE_BIRTHChanged();
    partial void OnBIRTHDATEChanging(System.Nullable<System.DateTime> value);
    partial void OnBIRTHDATEChanged();
    partial void OnAGEChanging(System.Nullable<int> value);
    partial void OnAGEChanged();
    partial void OnWEIGHTChanging(System.Nullable<int> value);
    partial void OnWEIGHTChanged();
    partial void OnHEIGHTChanging(System.Nullable<int> value);
    partial void OnHEIGHTChanged();
    partial void OnADDR_ROW1Changing(string value);
    partial void OnADDR_ROW1Changed();
    partial void OnADDR_ROW2Changing(string value);
    partial void OnADDR_ROW2Changed();
    partial void OnADDR_ROW3Changing(string value);
    partial void OnADDR_ROW3Changed();
    partial void OnADDR_HOME1Changing(string value);
    partial void OnADDR_HOME1Changed();
    partial void OnADDR_HOME2Changing(string value);
    partial void OnADDR_HOME2Changed();
    partial void OnADDR_HOME3Changing(string value);
    partial void OnADDR_HOME3Changed();
    partial void OnADDR_TELChanging(string value);
    partial void OnADDR_TELChanged();
    partial void OnADDR_MOBILEChanging(string value);
    partial void OnADDR_MOBILEChanged();
    partial void OnADDR_EMAILChanging(string value);
    partial void OnADDR_EMAILChanged();
    partial void OnADDR_PHOTOChanging(string value);
    partial void OnADDR_PHOTOChanged();
    partial void OnFLAGChanging(System.Nullable<int> value);
    partial void OnFLAGChanged();
    #endregion
		
		public STEP_ONE()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_USERNO", DbType="VarChar(15) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string USERNO
		{
			get
			{
				return this._USERNO;
			}
			set
			{
				if ((this._USERNO != value))
				{
					this.OnUSERNOChanging(value);
					this.SendPropertyChanging();
					this._USERNO = value;
					this.SendPropertyChanged("USERNO");
					this.OnUSERNOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_POSITION", DbType="VarChar(100)")]
		public string POSITION
		{
			get
			{
				return this._POSITION;
			}
			set
			{
				if ((this._POSITION != value))
				{
					this.OnPOSITIONChanging(value);
					this.SendPropertyChanging();
					this._POSITION = value;
					this.SendPropertyChanged("POSITION");
					this.OnPOSITIONChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FULLNAME_TH", DbType="VarChar(100)")]
		public string FULLNAME_TH
		{
			get
			{
				return this._FULLNAME_TH;
			}
			set
			{
				if ((this._FULLNAME_TH != value))
				{
					this.OnFULLNAME_THChanging(value);
					this.SendPropertyChanging();
					this._FULLNAME_TH = value;
					this.SendPropertyChanged("FULLNAME_TH");
					this.OnFULLNAME_THChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NICKNAME_TH", DbType="VarChar(50)")]
		public string NICKNAME_TH
		{
			get
			{
				return this._NICKNAME_TH;
			}
			set
			{
				if ((this._NICKNAME_TH != value))
				{
					this.OnNICKNAME_THChanging(value);
					this.SendPropertyChanging();
					this._NICKNAME_TH = value;
					this.SendPropertyChanged("NICKNAME_TH");
					this.OnNICKNAME_THChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FULLNAME_EN", DbType="VarChar(100)")]
		public string FULLNAME_EN
		{
			get
			{
				return this._FULLNAME_EN;
			}
			set
			{
				if ((this._FULLNAME_EN != value))
				{
					this.OnFULLNAME_ENChanging(value);
					this.SendPropertyChanging();
					this._FULLNAME_EN = value;
					this.SendPropertyChanged("FULLNAME_EN");
					this.OnFULLNAME_ENChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NICKNAME_EN", DbType="VarChar(50)")]
		public string NICKNAME_EN
		{
			get
			{
				return this._NICKNAME_EN;
			}
			set
			{
				if ((this._NICKNAME_EN != value))
				{
					this.OnNICKNAME_ENChanging(value);
					this.SendPropertyChanging();
					this._NICKNAME_EN = value;
					this.SendPropertyChanged("NICKNAME_EN");
					this.OnNICKNAME_ENChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PEOPLEID", DbType="VarChar(20)")]
		public string PEOPLEID
		{
			get
			{
				return this._PEOPLEID;
			}
			set
			{
				if ((this._PEOPLEID != value))
				{
					this.OnPEOPLEIDChanging(value);
					this.SendPropertyChanging();
					this._PEOPLEID = value;
					this.SendPropertyChanged("PEOPLEID");
					this.OnPEOPLEIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ZONE", DbType="VarChar(50)")]
		public string ZONE
		{
			get
			{
				return this._ZONE;
			}
			set
			{
				if ((this._ZONE != value))
				{
					this.OnZONEChanging(value);
					this.SendPropertyChanging();
					this._ZONE = value;
					this.SendPropertyChanged("ZONE");
					this.OnZONEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PROVINCE_BIRTH", DbType="VarChar(50)")]
		public string PROVINCE_BIRTH
		{
			get
			{
				return this._PROVINCE_BIRTH;
			}
			set
			{
				if ((this._PROVINCE_BIRTH != value))
				{
					this.OnPROVINCE_BIRTHChanging(value);
					this.SendPropertyChanging();
					this._PROVINCE_BIRTH = value;
					this.SendPropertyChanged("PROVINCE_BIRTH");
					this.OnPROVINCE_BIRTHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BIRTHDATE", DbType="Date")]
		public System.Nullable<System.DateTime> BIRTHDATE
		{
			get
			{
				return this._BIRTHDATE;
			}
			set
			{
				if ((this._BIRTHDATE != value))
				{
					this.OnBIRTHDATEChanging(value);
					this.SendPropertyChanging();
					this._BIRTHDATE = value;
					this.SendPropertyChanged("BIRTHDATE");
					this.OnBIRTHDATEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AGE", DbType="Int")]
		public System.Nullable<int> AGE
		{
			get
			{
				return this._AGE;
			}
			set
			{
				if ((this._AGE != value))
				{
					this.OnAGEChanging(value);
					this.SendPropertyChanging();
					this._AGE = value;
					this.SendPropertyChanged("AGE");
					this.OnAGEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_WEIGHT", DbType="Int")]
		public System.Nullable<int> WEIGHT
		{
			get
			{
				return this._WEIGHT;
			}
			set
			{
				if ((this._WEIGHT != value))
				{
					this.OnWEIGHTChanging(value);
					this.SendPropertyChanging();
					this._WEIGHT = value;
					this.SendPropertyChanged("WEIGHT");
					this.OnWEIGHTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HEIGHT", DbType="Int")]
		public System.Nullable<int> HEIGHT
		{
			get
			{
				return this._HEIGHT;
			}
			set
			{
				if ((this._HEIGHT != value))
				{
					this.OnHEIGHTChanging(value);
					this.SendPropertyChanging();
					this._HEIGHT = value;
					this.SendPropertyChanged("HEIGHT");
					this.OnHEIGHTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ADDR_ROW1", DbType="VarChar(100)")]
		public string ADDR_ROW1
		{
			get
			{
				return this._ADDR_ROW1;
			}
			set
			{
				if ((this._ADDR_ROW1 != value))
				{
					this.OnADDR_ROW1Changing(value);
					this.SendPropertyChanging();
					this._ADDR_ROW1 = value;
					this.SendPropertyChanged("ADDR_ROW1");
					this.OnADDR_ROW1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ADDR_ROW2", DbType="VarChar(100)")]
		public string ADDR_ROW2
		{
			get
			{
				return this._ADDR_ROW2;
			}
			set
			{
				if ((this._ADDR_ROW2 != value))
				{
					this.OnADDR_ROW2Changing(value);
					this.SendPropertyChanging();
					this._ADDR_ROW2 = value;
					this.SendPropertyChanged("ADDR_ROW2");
					this.OnADDR_ROW2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ADDR_ROW3", DbType="VarChar(100)")]
		public string ADDR_ROW3
		{
			get
			{
				return this._ADDR_ROW3;
			}
			set
			{
				if ((this._ADDR_ROW3 != value))
				{
					this.OnADDR_ROW3Changing(value);
					this.SendPropertyChanging();
					this._ADDR_ROW3 = value;
					this.SendPropertyChanged("ADDR_ROW3");
					this.OnADDR_ROW3Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ADDR_HOME1", DbType="VarChar(100)")]
		public string ADDR_HOME1
		{
			get
			{
				return this._ADDR_HOME1;
			}
			set
			{
				if ((this._ADDR_HOME1 != value))
				{
					this.OnADDR_HOME1Changing(value);
					this.SendPropertyChanging();
					this._ADDR_HOME1 = value;
					this.SendPropertyChanged("ADDR_HOME1");
					this.OnADDR_HOME1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ADDR_HOME2", DbType="VarChar(100)")]
		public string ADDR_HOME2
		{
			get
			{
				return this._ADDR_HOME2;
			}
			set
			{
				if ((this._ADDR_HOME2 != value))
				{
					this.OnADDR_HOME2Changing(value);
					this.SendPropertyChanging();
					this._ADDR_HOME2 = value;
					this.SendPropertyChanged("ADDR_HOME2");
					this.OnADDR_HOME2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ADDR_HOME3", DbType="VarChar(100)")]
		public string ADDR_HOME3
		{
			get
			{
				return this._ADDR_HOME3;
			}
			set
			{
				if ((this._ADDR_HOME3 != value))
				{
					this.OnADDR_HOME3Changing(value);
					this.SendPropertyChanging();
					this._ADDR_HOME3 = value;
					this.SendPropertyChanged("ADDR_HOME3");
					this.OnADDR_HOME3Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ADDR_TEL", DbType="VarChar(15)")]
		public string ADDR_TEL
		{
			get
			{
				return this._ADDR_TEL;
			}
			set
			{
				if ((this._ADDR_TEL != value))
				{
					this.OnADDR_TELChanging(value);
					this.SendPropertyChanging();
					this._ADDR_TEL = value;
					this.SendPropertyChanged("ADDR_TEL");
					this.OnADDR_TELChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ADDR_MOBILE", DbType="VarChar(15)")]
		public string ADDR_MOBILE
		{
			get
			{
				return this._ADDR_MOBILE;
			}
			set
			{
				if ((this._ADDR_MOBILE != value))
				{
					this.OnADDR_MOBILEChanging(value);
					this.SendPropertyChanging();
					this._ADDR_MOBILE = value;
					this.SendPropertyChanged("ADDR_MOBILE");
					this.OnADDR_MOBILEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ADDR_EMAIL", DbType="VarChar(40)")]
		public string ADDR_EMAIL
		{
			get
			{
				return this._ADDR_EMAIL;
			}
			set
			{
				if ((this._ADDR_EMAIL != value))
				{
					this.OnADDR_EMAILChanging(value);
					this.SendPropertyChanging();
					this._ADDR_EMAIL = value;
					this.SendPropertyChanged("ADDR_EMAIL");
					this.OnADDR_EMAILChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ADDR_PHOTO", DbType="VarChar(MAX)")]
		public string ADDR_PHOTO
		{
			get
			{
				return this._ADDR_PHOTO;
			}
			set
			{
				if ((this._ADDR_PHOTO != value))
				{
					this.OnADDR_PHOTOChanging(value);
					this.SendPropertyChanging();
					this._ADDR_PHOTO = value;
					this.SendPropertyChanged("ADDR_PHOTO");
					this.OnADDR_PHOTOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FLAG", DbType="Int")]
		public System.Nullable<int> FLAG
		{
			get
			{
				return this._FLAG;
			}
			set
			{
				if ((this._FLAG != value))
				{
					this.OnFLAGChanging(value);
					this.SendPropertyChanging();
					this._FLAG = value;
					this.SendPropertyChanged("FLAG");
					this.OnFLAGChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.STEP_TWO")]
	public partial class STEP_TWO : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _USERNO;
		
		private System.Nullable<System.DateTime> _STARTING_DATE;
		
		private string _MARITAL;
		
		private System.Nullable<int> _CHILDEN;
		
		private string _SPOUSE_NAME;
		
		private System.Nullable<int> _SPOUSE_AGE;
		
		private string _SPOUSE_OCCUPATION;
		
		private string _SPOUSE_OFFICE;
		
		private string _SPOUSE_PHONE;
		
		private string _EMERGENCY;
		
		private string _EMERGENCY_ROW1;
		
		private string _EMERGENCY_ROW2;
		
		private string _EMERGENCY_RELATIONSHIP;
		
		private string _EMERGENCY_PHONE;
		
		private System.Nullable<int> _FLAG;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnUSERNOChanging(string value);
    partial void OnUSERNOChanged();
    partial void OnSTARTING_DATEChanging(System.Nullable<System.DateTime> value);
    partial void OnSTARTING_DATEChanged();
    partial void OnMARITALChanging(string value);
    partial void OnMARITALChanged();
    partial void OnCHILDENChanging(System.Nullable<int> value);
    partial void OnCHILDENChanged();
    partial void OnSPOUSE_NAMEChanging(string value);
    partial void OnSPOUSE_NAMEChanged();
    partial void OnSPOUSE_AGEChanging(System.Nullable<int> value);
    partial void OnSPOUSE_AGEChanged();
    partial void OnSPOUSE_OCCUPATIONChanging(string value);
    partial void OnSPOUSE_OCCUPATIONChanged();
    partial void OnSPOUSE_OFFICEChanging(string value);
    partial void OnSPOUSE_OFFICEChanged();
    partial void OnSPOUSE_PHONEChanging(string value);
    partial void OnSPOUSE_PHONEChanged();
    partial void OnEMERGENCYChanging(string value);
    partial void OnEMERGENCYChanged();
    partial void OnEMERGENCY_ROW1Changing(string value);
    partial void OnEMERGENCY_ROW1Changed();
    partial void OnEMERGENCY_ROW2Changing(string value);
    partial void OnEMERGENCY_ROW2Changed();
    partial void OnEMERGENCY_RELATIONSHIPChanging(string value);
    partial void OnEMERGENCY_RELATIONSHIPChanged();
    partial void OnEMERGENCY_PHONEChanging(string value);
    partial void OnEMERGENCY_PHONEChanged();
    partial void OnFLAGChanging(System.Nullable<int> value);
    partial void OnFLAGChanged();
    #endregion
		
		public STEP_TWO()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_USERNO", DbType="VarChar(15) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string USERNO
		{
			get
			{
				return this._USERNO;
			}
			set
			{
				if ((this._USERNO != value))
				{
					this.OnUSERNOChanging(value);
					this.SendPropertyChanging();
					this._USERNO = value;
					this.SendPropertyChanged("USERNO");
					this.OnUSERNOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_STARTING_DATE", DbType="Date")]
		public System.Nullable<System.DateTime> STARTING_DATE
		{
			get
			{
				return this._STARTING_DATE;
			}
			set
			{
				if ((this._STARTING_DATE != value))
				{
					this.OnSTARTING_DATEChanging(value);
					this.SendPropertyChanging();
					this._STARTING_DATE = value;
					this.SendPropertyChanged("STARTING_DATE");
					this.OnSTARTING_DATEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MARITAL", DbType="VarChar(20)")]
		public string MARITAL
		{
			get
			{
				return this._MARITAL;
			}
			set
			{
				if ((this._MARITAL != value))
				{
					this.OnMARITALChanging(value);
					this.SendPropertyChanging();
					this._MARITAL = value;
					this.SendPropertyChanged("MARITAL");
					this.OnMARITALChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CHILDEN", DbType="Int")]
		public System.Nullable<int> CHILDEN
		{
			get
			{
				return this._CHILDEN;
			}
			set
			{
				if ((this._CHILDEN != value))
				{
					this.OnCHILDENChanging(value);
					this.SendPropertyChanging();
					this._CHILDEN = value;
					this.SendPropertyChanged("CHILDEN");
					this.OnCHILDENChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SPOUSE_NAME", DbType="VarChar(100)")]
		public string SPOUSE_NAME
		{
			get
			{
				return this._SPOUSE_NAME;
			}
			set
			{
				if ((this._SPOUSE_NAME != value))
				{
					this.OnSPOUSE_NAMEChanging(value);
					this.SendPropertyChanging();
					this._SPOUSE_NAME = value;
					this.SendPropertyChanged("SPOUSE_NAME");
					this.OnSPOUSE_NAMEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SPOUSE_AGE", DbType="Int")]
		public System.Nullable<int> SPOUSE_AGE
		{
			get
			{
				return this._SPOUSE_AGE;
			}
			set
			{
				if ((this._SPOUSE_AGE != value))
				{
					this.OnSPOUSE_AGEChanging(value);
					this.SendPropertyChanging();
					this._SPOUSE_AGE = value;
					this.SendPropertyChanged("SPOUSE_AGE");
					this.OnSPOUSE_AGEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SPOUSE_OCCUPATION", DbType="VarChar(75)")]
		public string SPOUSE_OCCUPATION
		{
			get
			{
				return this._SPOUSE_OCCUPATION;
			}
			set
			{
				if ((this._SPOUSE_OCCUPATION != value))
				{
					this.OnSPOUSE_OCCUPATIONChanging(value);
					this.SendPropertyChanging();
					this._SPOUSE_OCCUPATION = value;
					this.SendPropertyChanged("SPOUSE_OCCUPATION");
					this.OnSPOUSE_OCCUPATIONChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SPOUSE_OFFICE", DbType="VarChar(100)")]
		public string SPOUSE_OFFICE
		{
			get
			{
				return this._SPOUSE_OFFICE;
			}
			set
			{
				if ((this._SPOUSE_OFFICE != value))
				{
					this.OnSPOUSE_OFFICEChanging(value);
					this.SendPropertyChanging();
					this._SPOUSE_OFFICE = value;
					this.SendPropertyChanged("SPOUSE_OFFICE");
					this.OnSPOUSE_OFFICEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SPOUSE_PHONE", DbType="VarChar(15)")]
		public string SPOUSE_PHONE
		{
			get
			{
				return this._SPOUSE_PHONE;
			}
			set
			{
				if ((this._SPOUSE_PHONE != value))
				{
					this.OnSPOUSE_PHONEChanging(value);
					this.SendPropertyChanging();
					this._SPOUSE_PHONE = value;
					this.SendPropertyChanged("SPOUSE_PHONE");
					this.OnSPOUSE_PHONEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EMERGENCY", DbType="VarChar(100)")]
		public string EMERGENCY
		{
			get
			{
				return this._EMERGENCY;
			}
			set
			{
				if ((this._EMERGENCY != value))
				{
					this.OnEMERGENCYChanging(value);
					this.SendPropertyChanging();
					this._EMERGENCY = value;
					this.SendPropertyChanged("EMERGENCY");
					this.OnEMERGENCYChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EMERGENCY_ROW1", DbType="VarChar(100)")]
		public string EMERGENCY_ROW1
		{
			get
			{
				return this._EMERGENCY_ROW1;
			}
			set
			{
				if ((this._EMERGENCY_ROW1 != value))
				{
					this.OnEMERGENCY_ROW1Changing(value);
					this.SendPropertyChanging();
					this._EMERGENCY_ROW1 = value;
					this.SendPropertyChanged("EMERGENCY_ROW1");
					this.OnEMERGENCY_ROW1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EMERGENCY_ROW2", DbType="VarChar(100)")]
		public string EMERGENCY_ROW2
		{
			get
			{
				return this._EMERGENCY_ROW2;
			}
			set
			{
				if ((this._EMERGENCY_ROW2 != value))
				{
					this.OnEMERGENCY_ROW2Changing(value);
					this.SendPropertyChanging();
					this._EMERGENCY_ROW2 = value;
					this.SendPropertyChanged("EMERGENCY_ROW2");
					this.OnEMERGENCY_ROW2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EMERGENCY_RELATIONSHIP", DbType="VarChar(20)")]
		public string EMERGENCY_RELATIONSHIP
		{
			get
			{
				return this._EMERGENCY_RELATIONSHIP;
			}
			set
			{
				if ((this._EMERGENCY_RELATIONSHIP != value))
				{
					this.OnEMERGENCY_RELATIONSHIPChanging(value);
					this.SendPropertyChanging();
					this._EMERGENCY_RELATIONSHIP = value;
					this.SendPropertyChanged("EMERGENCY_RELATIONSHIP");
					this.OnEMERGENCY_RELATIONSHIPChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EMERGENCY_PHONE", DbType="VarChar(15)")]
		public string EMERGENCY_PHONE
		{
			get
			{
				return this._EMERGENCY_PHONE;
			}
			set
			{
				if ((this._EMERGENCY_PHONE != value))
				{
					this.OnEMERGENCY_PHONEChanging(value);
					this.SendPropertyChanging();
					this._EMERGENCY_PHONE = value;
					this.SendPropertyChanged("EMERGENCY_PHONE");
					this.OnEMERGENCY_PHONEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FLAG", DbType="Int")]
		public System.Nullable<int> FLAG
		{
			get
			{
				return this._FLAG;
			}
			set
			{
				if ((this._FLAG != value))
				{
					this.OnFLAGChanging(value);
					this.SendPropertyChanging();
					this._FLAG = value;
					this.SendPropertyChanged("FLAG");
					this.OnFLAGChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.STEP_THREE_DETAIL")]
	public partial class STEP_THREE_DETAIL : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _USERNO;
		
		private string _CURRENTLY_STUDY;
		
		private string _STUDY_NAME;
		
		private string _STUDY_MAJOR;
		
		private string _HOBBY_ROW1;
		
		private string _HOBBY_ROW2;
		
		private string _HOBBY_ROW3;
		
		private string _HOBBY_ROW4;
		
		private System.Nullable<int> _FLAG;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnUSERNOChanging(string value);
    partial void OnUSERNOChanged();
    partial void OnCURRENTLY_STUDYChanging(string value);
    partial void OnCURRENTLY_STUDYChanged();
    partial void OnSTUDY_NAMEChanging(string value);
    partial void OnSTUDY_NAMEChanged();
    partial void OnSTUDY_MAJORChanging(string value);
    partial void OnSTUDY_MAJORChanged();
    partial void OnHOBBY_ROW1Changing(string value);
    partial void OnHOBBY_ROW1Changed();
    partial void OnHOBBY_ROW2Changing(string value);
    partial void OnHOBBY_ROW2Changed();
    partial void OnHOBBY_ROW3Changing(string value);
    partial void OnHOBBY_ROW3Changed();
    partial void OnHOBBY_ROW4Changing(string value);
    partial void OnHOBBY_ROW4Changed();
    partial void OnFLAGChanging(System.Nullable<int> value);
    partial void OnFLAGChanged();
    #endregion
		
		public STEP_THREE_DETAIL()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_USERNO", DbType="VarChar(20) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string USERNO
		{
			get
			{
				return this._USERNO;
			}
			set
			{
				if ((this._USERNO != value))
				{
					this.OnUSERNOChanging(value);
					this.SendPropertyChanging();
					this._USERNO = value;
					this.SendPropertyChanged("USERNO");
					this.OnUSERNOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CURRENTLY_STUDY", DbType="VarChar(5)")]
		public string CURRENTLY_STUDY
		{
			get
			{
				return this._CURRENTLY_STUDY;
			}
			set
			{
				if ((this._CURRENTLY_STUDY != value))
				{
					this.OnCURRENTLY_STUDYChanging(value);
					this.SendPropertyChanging();
					this._CURRENTLY_STUDY = value;
					this.SendPropertyChanged("CURRENTLY_STUDY");
					this.OnCURRENTLY_STUDYChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_STUDY_NAME", DbType="VarChar(50)")]
		public string STUDY_NAME
		{
			get
			{
				return this._STUDY_NAME;
			}
			set
			{
				if ((this._STUDY_NAME != value))
				{
					this.OnSTUDY_NAMEChanging(value);
					this.SendPropertyChanging();
					this._STUDY_NAME = value;
					this.SendPropertyChanged("STUDY_NAME");
					this.OnSTUDY_NAMEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_STUDY_MAJOR", DbType="VarChar(50)")]
		public string STUDY_MAJOR
		{
			get
			{
				return this._STUDY_MAJOR;
			}
			set
			{
				if ((this._STUDY_MAJOR != value))
				{
					this.OnSTUDY_MAJORChanging(value);
					this.SendPropertyChanging();
					this._STUDY_MAJOR = value;
					this.SendPropertyChanged("STUDY_MAJOR");
					this.OnSTUDY_MAJORChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HOBBY_ROW1", DbType="VarChar(20)")]
		public string HOBBY_ROW1
		{
			get
			{
				return this._HOBBY_ROW1;
			}
			set
			{
				if ((this._HOBBY_ROW1 != value))
				{
					this.OnHOBBY_ROW1Changing(value);
					this.SendPropertyChanging();
					this._HOBBY_ROW1 = value;
					this.SendPropertyChanged("HOBBY_ROW1");
					this.OnHOBBY_ROW1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HOBBY_ROW2", DbType="VarChar(20)")]
		public string HOBBY_ROW2
		{
			get
			{
				return this._HOBBY_ROW2;
			}
			set
			{
				if ((this._HOBBY_ROW2 != value))
				{
					this.OnHOBBY_ROW2Changing(value);
					this.SendPropertyChanging();
					this._HOBBY_ROW2 = value;
					this.SendPropertyChanged("HOBBY_ROW2");
					this.OnHOBBY_ROW2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HOBBY_ROW3", DbType="VarChar(20)")]
		public string HOBBY_ROW3
		{
			get
			{
				return this._HOBBY_ROW3;
			}
			set
			{
				if ((this._HOBBY_ROW3 != value))
				{
					this.OnHOBBY_ROW3Changing(value);
					this.SendPropertyChanging();
					this._HOBBY_ROW3 = value;
					this.SendPropertyChanged("HOBBY_ROW3");
					this.OnHOBBY_ROW3Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HOBBY_ROW4", DbType="VarChar(20)")]
		public string HOBBY_ROW4
		{
			get
			{
				return this._HOBBY_ROW4;
			}
			set
			{
				if ((this._HOBBY_ROW4 != value))
				{
					this.OnHOBBY_ROW4Changing(value);
					this.SendPropertyChanging();
					this._HOBBY_ROW4 = value;
					this.SendPropertyChanged("HOBBY_ROW4");
					this.OnHOBBY_ROW4Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FLAG", DbType="Int")]
		public System.Nullable<int> FLAG
		{
			get
			{
				return this._FLAG;
			}
			set
			{
				if ((this._FLAG != value))
				{
					this.OnFLAGChanging(value);
					this.SendPropertyChanging();
					this._FLAG = value;
					this.SendPropertyChanged("FLAG");
					this.OnFLAGChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.STEP_THREE_EDUCTION")]
	public partial class STEP_THREE_EDUCTION
	{
		
		private string _USERNO;
		
		private string _EDUCATION_LV;
		
		private string _EDUCATION_NAME;
		
		private string _DEGREE;
		
		private string _S_YEAR;
		
		private string _E_YEAR;
		
		private System.Nullable<decimal> _GPA;
		
		private string _MAJOR;
		
		private System.Nullable<int> _FLAG;
		
		public STEP_THREE_EDUCTION()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_USERNO", DbType="VarChar(15) NOT NULL", CanBeNull=false)]
		public string USERNO
		{
			get
			{
				return this._USERNO;
			}
			set
			{
				if ((this._USERNO != value))
				{
					this._USERNO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EDUCATION_LV", DbType="VarChar(50)")]
		public string EDUCATION_LV
		{
			get
			{
				return this._EDUCATION_LV;
			}
			set
			{
				if ((this._EDUCATION_LV != value))
				{
					this._EDUCATION_LV = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EDUCATION_NAME", DbType="VarChar(100)")]
		public string EDUCATION_NAME
		{
			get
			{
				return this._EDUCATION_NAME;
			}
			set
			{
				if ((this._EDUCATION_NAME != value))
				{
					this._EDUCATION_NAME = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DEGREE", DbType="VarChar(50)")]
		public string DEGREE
		{
			get
			{
				return this._DEGREE;
			}
			set
			{
				if ((this._DEGREE != value))
				{
					this._DEGREE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_S_YEAR", DbType="VarChar(5)")]
		public string S_YEAR
		{
			get
			{
				return this._S_YEAR;
			}
			set
			{
				if ((this._S_YEAR != value))
				{
					this._S_YEAR = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_E_YEAR", DbType="VarChar(5)")]
		public string E_YEAR
		{
			get
			{
				return this._E_YEAR;
			}
			set
			{
				if ((this._E_YEAR != value))
				{
					this._E_YEAR = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GPA", DbType="Decimal(18,2)")]
		public System.Nullable<decimal> GPA
		{
			get
			{
				return this._GPA;
			}
			set
			{
				if ((this._GPA != value))
				{
					this._GPA = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MAJOR", DbType="VarChar(50)")]
		public string MAJOR
		{
			get
			{
				return this._MAJOR;
			}
			set
			{
				if ((this._MAJOR != value))
				{
					this._MAJOR = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FLAG", DbType="Int")]
		public System.Nullable<int> FLAG
		{
			get
			{
				return this._FLAG;
			}
			set
			{
				if ((this._FLAG != value))
				{
					this._FLAG = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.STEP_THREE_EMPLOYMENT")]
	public partial class STEP_THREE_EMPLOYMENT
	{
		
		private string _USERNO;
		
		private string _COMPANY_NAME;
		
		private System.Nullable<System.DateTime> _S_DATE;
		
		private System.Nullable<System.DateTime> _E_DATE;
		
		private string _POSITION;
		
		private System.Nullable<int> _SALARY;
		
		private string _DETAIL;
		
		private string _LEAVING;
		
		private System.Nullable<int> _FLAG;
		
		public STEP_THREE_EMPLOYMENT()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_USERNO", DbType="VarChar(15) NOT NULL", CanBeNull=false)]
		public string USERNO
		{
			get
			{
				return this._USERNO;
			}
			set
			{
				if ((this._USERNO != value))
				{
					this._USERNO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_COMPANY_NAME", DbType="VarChar(50)")]
		public string COMPANY_NAME
		{
			get
			{
				return this._COMPANY_NAME;
			}
			set
			{
				if ((this._COMPANY_NAME != value))
				{
					this._COMPANY_NAME = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_S_DATE", DbType="Date")]
		public System.Nullable<System.DateTime> S_DATE
		{
			get
			{
				return this._S_DATE;
			}
			set
			{
				if ((this._S_DATE != value))
				{
					this._S_DATE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_E_DATE", DbType="Date")]
		public System.Nullable<System.DateTime> E_DATE
		{
			get
			{
				return this._E_DATE;
			}
			set
			{
				if ((this._E_DATE != value))
				{
					this._E_DATE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_POSITION", DbType="VarChar(50)")]
		public string POSITION
		{
			get
			{
				return this._POSITION;
			}
			set
			{
				if ((this._POSITION != value))
				{
					this._POSITION = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SALARY", DbType="Int")]
		public System.Nullable<int> SALARY
		{
			get
			{
				return this._SALARY;
			}
			set
			{
				if ((this._SALARY != value))
				{
					this._SALARY = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DETAIL", DbType="VarChar(50)")]
		public string DETAIL
		{
			get
			{
				return this._DETAIL;
			}
			set
			{
				if ((this._DETAIL != value))
				{
					this._DETAIL = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LEAVING", DbType="VarChar(50)")]
		public string LEAVING
		{
			get
			{
				return this._LEAVING;
			}
			set
			{
				if ((this._LEAVING != value))
				{
					this._LEAVING = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FLAG", DbType="Int")]
		public System.Nullable<int> FLAG
		{
			get
			{
				return this._FLAG;
			}
			set
			{
				if ((this._FLAG != value))
				{
					this._FLAG = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.STEP_THREE_LANGUAGE")]
	public partial class STEP_THREE_LANGUAGE
	{
		
		private string _USERNO;
		
		private string _LANGUAGE;
		
		private string _SPEAKING;
		
		private string _READING;
		
		private string _WRITING;
		
		private System.Nullable<int> _FLAG;
		
		public STEP_THREE_LANGUAGE()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_USERNO", DbType="VarChar(15) NOT NULL", CanBeNull=false)]
		public string USERNO
		{
			get
			{
				return this._USERNO;
			}
			set
			{
				if ((this._USERNO != value))
				{
					this._USERNO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LANGUAGE", DbType="VarChar(20)")]
		public string LANGUAGE
		{
			get
			{
				return this._LANGUAGE;
			}
			set
			{
				if ((this._LANGUAGE != value))
				{
					this._LANGUAGE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SPEAKING", DbType="VarChar(10)")]
		public string SPEAKING
		{
			get
			{
				return this._SPEAKING;
			}
			set
			{
				if ((this._SPEAKING != value))
				{
					this._SPEAKING = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_READING", DbType="VarChar(10)")]
		public string READING
		{
			get
			{
				return this._READING;
			}
			set
			{
				if ((this._READING != value))
				{
					this._READING = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_WRITING", DbType="VarChar(10)")]
		public string WRITING
		{
			get
			{
				return this._WRITING;
			}
			set
			{
				if ((this._WRITING != value))
				{
					this._WRITING = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FLAG", DbType="Int")]
		public System.Nullable<int> FLAG
		{
			get
			{
				return this._FLAG;
			}
			set
			{
				if ((this._FLAG != value))
				{
					this._FLAG = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.STEP_THREE_TRAINING")]
	public partial class STEP_THREE_TRAINING
	{
		
		private string _USERNO;
		
		private System.Nullable<System.DateTime> _DATE;
		
		private string _COURSE;
		
		private string _INSTITUTION;
		
		private System.Nullable<System.DateTime> _S_DATE;
		
		private System.Nullable<System.DateTime> _E_DATE;
		
		private System.Nullable<int> _FLAG;
		
		public STEP_THREE_TRAINING()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_USERNO", DbType="VarChar(15) NOT NULL", CanBeNull=false)]
		public string USERNO
		{
			get
			{
				return this._USERNO;
			}
			set
			{
				if ((this._USERNO != value))
				{
					this._USERNO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DATE", DbType="Date")]
		public System.Nullable<System.DateTime> DATE
		{
			get
			{
				return this._DATE;
			}
			set
			{
				if ((this._DATE != value))
				{
					this._DATE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_COURSE", DbType="VarChar(100)")]
		public string COURSE
		{
			get
			{
				return this._COURSE;
			}
			set
			{
				if ((this._COURSE != value))
				{
					this._COURSE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_INSTITUTION", DbType="VarChar(100)")]
		public string INSTITUTION
		{
			get
			{
				return this._INSTITUTION;
			}
			set
			{
				if ((this._INSTITUTION != value))
				{
					this._INSTITUTION = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_S_DATE", DbType="Date")]
		public System.Nullable<System.DateTime> S_DATE
		{
			get
			{
				return this._S_DATE;
			}
			set
			{
				if ((this._S_DATE != value))
				{
					this._S_DATE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_E_DATE", DbType="Date")]
		public System.Nullable<System.DateTime> E_DATE
		{
			get
			{
				return this._E_DATE;
			}
			set
			{
				if ((this._E_DATE != value))
				{
					this._E_DATE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FLAG", DbType="Int")]
		public System.Nullable<int> FLAG
		{
			get
			{
				return this._FLAG;
			}
			set
			{
				if ((this._FLAG != value))
				{
					this._FLAG = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.STEP_FOUR")]
	public partial class STEP_FOUR
	{
		
		private string _USERNO;
		
		private System.Nullable<int> _Q_ID;
		
		private string _CHOOSE;
		
		private string _DETAIL_ROW1;
		
		private string _DETAIL_ROW2;
		
		private string _DETAIL_ROW3;
		
		private System.Nullable<int> _FLAG;
		
		public STEP_FOUR()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_USERNO", DbType="VarChar(15)")]
		public string USERNO
		{
			get
			{
				return this._USERNO;
			}
			set
			{
				if ((this._USERNO != value))
				{
					this._USERNO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Q_ID", DbType="Int")]
		public System.Nullable<int> Q_ID
		{
			get
			{
				return this._Q_ID;
			}
			set
			{
				if ((this._Q_ID != value))
				{
					this._Q_ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CHOOSE", DbType="VarChar(5)")]
		public string CHOOSE
		{
			get
			{
				return this._CHOOSE;
			}
			set
			{
				if ((this._CHOOSE != value))
				{
					this._CHOOSE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DETAIL_ROW1", DbType="VarChar(50)")]
		public string DETAIL_ROW1
		{
			get
			{
				return this._DETAIL_ROW1;
			}
			set
			{
				if ((this._DETAIL_ROW1 != value))
				{
					this._DETAIL_ROW1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DETAIL_ROW2", DbType="VarChar(50)")]
		public string DETAIL_ROW2
		{
			get
			{
				return this._DETAIL_ROW2;
			}
			set
			{
				if ((this._DETAIL_ROW2 != value))
				{
					this._DETAIL_ROW2 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DETAIL_ROW3", DbType="VarChar(50)")]
		public string DETAIL_ROW3
		{
			get
			{
				return this._DETAIL_ROW3;
			}
			set
			{
				if ((this._DETAIL_ROW3 != value))
				{
					this._DETAIL_ROW3 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FLAG", DbType="Int")]
		public System.Nullable<int> FLAG
		{
			get
			{
				return this._FLAG;
			}
			set
			{
				if ((this._FLAG != value))
				{
					this._FLAG = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
