#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAPI.DATA.HR_SALE
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="HR-SALE")]
	public partial class HR_SALEDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertMAS_USER_SYSTEM(MAS_USER_SYSTEM instance);
    partial void UpdateMAS_USER_SYSTEM(MAS_USER_SYSTEM instance);
    partial void DeleteMAS_USER_SYSTEM(MAS_USER_SYSTEM instance);
    partial void InsertMAS_POSITION(MAS_POSITION instance);
    partial void UpdateMAS_POSITION(MAS_POSITION instance);
    partial void DeleteMAS_POSITION(MAS_POSITION instance);
    partial void InsertHR_SALE_USER(HR_SALE_USER instance);
    partial void UpdateHR_SALE_USER(HR_SALE_USER instance);
    partial void DeleteHR_SALE_USER(HR_SALE_USER instance);
    partial void InsertHR_SALE_PT(HR_SALE_PT instance);
    partial void UpdateHR_SALE_PT(HR_SALE_PT instance);
    partial void DeleteHR_SALE_PT(HR_SALE_PT instance);
    partial void InsertHR_SALE_PI(HR_SALE_PI instance);
    partial void UpdateHR_SALE_PI(HR_SALE_PI instance);
    partial void DeleteHR_SALE_PI(HR_SALE_PI instance);
    partial void InsertHR_LVL(HR_LVL instance);
    partial void UpdateHR_LVL(HR_LVL instance);
    partial void DeleteHR_LVL(HR_LVL instance);
    #endregion
		
		public HR_SALEDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["HR_SALEConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public HR_SALEDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public HR_SALEDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public HR_SALEDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public HR_SALEDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<MAS_USER_SYSTEM> MAS_USER_SYSTEMs
		{
			get
			{
				return this.GetTable<MAS_USER_SYSTEM>();
			}
		}
		
		public System.Data.Linq.Table<MAS_POSITION> MAS_POSITIONs
		{
			get
			{
				return this.GetTable<MAS_POSITION>();
			}
		}
		
		public System.Data.Linq.Table<HR_SALE_USER> HR_SALE_USERs
		{
			get
			{
				return this.GetTable<HR_SALE_USER>();
			}
		}
		
		public System.Data.Linq.Table<HR_SALE_PT> HR_SALE_PTs
		{
			get
			{
				return this.GetTable<HR_SALE_PT>();
			}
		}
		
		public System.Data.Linq.Table<HR_SALE_PI> HR_SALE_PIs
		{
			get
			{
				return this.GetTable<HR_SALE_PI>();
			}
		}
		
		public System.Data.Linq.Table<HR_LVL> HR_LVLs
		{
			get
			{
				return this.GetTable<HR_LVL>();
			}
		}
		
		public System.Data.Linq.Table<VW_DEP> VW_DEPs
		{
			get
			{
				return this.GetTable<VW_DEP>();
			}
		}
		
		public System.Data.Linq.Table<VW_USER_PRO> VW_USER_PROs
		{
			get
			{
				return this.GetTable<VW_USER_PRO>();
			}
		}
		
		public System.Data.Linq.Table<VW_SHOW_PRODUCT> VW_SHOW_PRODUCTs
		{
			get
			{
				return this.GetTable<VW_SHOW_PRODUCT>();
			}
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.HR_SALE_ADDUSER")]
		public int HR_SALE_ADDUSER([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(5)")] string user)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), user);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.HR_SALE_GetALLManagement")]
		public ISingleResult<HR_SALE_GetALLManagementResult> HR_SALE_GetALLManagement()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<HR_SALE_GetALLManagementResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.HR_SALE_GetBal")]
		public ISingleResult<HR_SALE_GetBalResult> HR_SALE_GetBal([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(20)")] string user)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), user);
			return ((ISingleResult<HR_SALE_GetBalResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.HR_SALE_GetManagement")]
		public ISingleResult<HR_SALE_GetManagementResult> HR_SALE_GetManagement()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<HR_SALE_GetManagementResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.HR_SALE_GETUSER")]
		public ISingleResult<HR_SALE_GETUSERResult> HR_SALE_GETUSER([global::System.Data.Linq.Mapping.ParameterAttribute(Name="ID_user", DbType="VarChar(20)")] string iD_user)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), iD_user);
			return ((ISingleResult<HR_SALE_GETUSERResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.HR_SALE_ShowHistory")]
		public ISingleResult<HR_SALE_ShowHistoryResult> HR_SALE_ShowHistory([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(20)")] string user)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), user);
			return ((ISingleResult<HR_SALE_ShowHistoryResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.HR_SALE_ShowPI")]
		public ISingleResult<HR_SALE_ShowPIResult> HR_SALE_ShowPI([global::System.Data.Linq.Mapping.ParameterAttribute(Name="ID_user", DbType="VarChar(20)")] string iD_user, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ABBNO", DbType="VarChar(20)")] string aBBNO)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), iD_user, aBBNO);
			return ((ISingleResult<HR_SALE_ShowPIResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.HR_SALE_POS")]
		public ISingleResult<HR_SALE_POSResult> HR_SALE_POS()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<HR_SALE_POSResult>)(result.ReturnValue));
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.MAS_USER_SYSTEM")]
	public partial class MAS_USER_SYSTEM : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _STCODE;
		
		private string _PASS;
		
		private string _POSITION;
		
		private string _DEGREE;
		
		private string _DPCODE;
		
		private string _DPNAME;
		
		private string _FULLNAME;
		
		private string _FULLNAME_EN;
		
		private string _EMAIL;
		
		private string _NICKNAME;
		
		private System.Nullable<System.DateTime> _STARTDATE;
		
		private System.Nullable<System.DateTime> _ENDDATE;
		
		private System.Nullable<System.DateTime> _BIRTHDATE;
		
		private System.Nullable<int> _FLAG;
		
		private byte _DELETED;
		
		private System.Nullable<System.DateTime> _DATECREATE;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnSTCODEChanging(string value);
    partial void OnSTCODEChanged();
    partial void OnPASSChanging(string value);
    partial void OnPASSChanged();
    partial void OnPOSITIONChanging(string value);
    partial void OnPOSITIONChanged();
    partial void OnDEGREEChanging(string value);
    partial void OnDEGREEChanged();
    partial void OnDPCODEChanging(string value);
    partial void OnDPCODEChanged();
    partial void OnDPNAMEChanging(string value);
    partial void OnDPNAMEChanged();
    partial void OnFULLNAMEChanging(string value);
    partial void OnFULLNAMEChanged();
    partial void OnFULLNAME_ENChanging(string value);
    partial void OnFULLNAME_ENChanged();
    partial void OnEMAILChanging(string value);
    partial void OnEMAILChanged();
    partial void OnNICKNAMEChanging(string value);
    partial void OnNICKNAMEChanged();
    partial void OnSTARTDATEChanging(System.Nullable<System.DateTime> value);
    partial void OnSTARTDATEChanged();
    partial void OnENDDATEChanging(System.Nullable<System.DateTime> value);
    partial void OnENDDATEChanged();
    partial void OnBIRTHDATEChanging(System.Nullable<System.DateTime> value);
    partial void OnBIRTHDATEChanged();
    partial void OnFLAGChanging(System.Nullable<int> value);
    partial void OnFLAGChanged();
    partial void OnDELETEDChanging(byte value);
    partial void OnDELETEDChanged();
    partial void OnDATECREATEChanging(System.Nullable<System.DateTime> value);
    partial void OnDATECREATEChanged();
    #endregion
		
		public MAS_USER_SYSTEM()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_STCODE", DbType="VarChar(5) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string STCODE
		{
			get
			{
				return this._STCODE;
			}
			set
			{
				if ((this._STCODE != value))
				{
					this.OnSTCODEChanging(value);
					this.SendPropertyChanging();
					this._STCODE = value;
					this.SendPropertyChanged("STCODE");
					this.OnSTCODEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PASS", DbType="VarChar(20)")]
		public string PASS
		{
			get
			{
				return this._PASS;
			}
			set
			{
				if ((this._PASS != value))
				{
					this.OnPASSChanging(value);
					this.SendPropertyChanging();
					this._PASS = value;
					this.SendPropertyChanged("PASS");
					this.OnPASSChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_POSITION", DbType="VarChar(25)")]
		public string POSITION
		{
			get
			{
				return this._POSITION;
			}
			set
			{
				if ((this._POSITION != value))
				{
					this.OnPOSITIONChanging(value);
					this.SendPropertyChanging();
					this._POSITION = value;
					this.SendPropertyChanged("POSITION");
					this.OnPOSITIONChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DEGREE", DbType="VarChar(10)")]
		public string DEGREE
		{
			get
			{
				return this._DEGREE;
			}
			set
			{
				if ((this._DEGREE != value))
				{
					this.OnDEGREEChanging(value);
					this.SendPropertyChanging();
					this._DEGREE = value;
					this.SendPropertyChanged("DEGREE");
					this.OnDEGREEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DPCODE", DbType="VarChar(10)")]
		public string DPCODE
		{
			get
			{
				return this._DPCODE;
			}
			set
			{
				if ((this._DPCODE != value))
				{
					this.OnDPCODEChanging(value);
					this.SendPropertyChanging();
					this._DPCODE = value;
					this.SendPropertyChanged("DPCODE");
					this.OnDPCODEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DPNAME", DbType="VarChar(70)")]
		public string DPNAME
		{
			get
			{
				return this._DPNAME;
			}
			set
			{
				if ((this._DPNAME != value))
				{
					this.OnDPNAMEChanging(value);
					this.SendPropertyChanging();
					this._DPNAME = value;
					this.SendPropertyChanged("DPNAME");
					this.OnDPNAMEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FULLNAME", DbType="VarChar(70)")]
		public string FULLNAME
		{
			get
			{
				return this._FULLNAME;
			}
			set
			{
				if ((this._FULLNAME != value))
				{
					this.OnFULLNAMEChanging(value);
					this.SendPropertyChanging();
					this._FULLNAME = value;
					this.SendPropertyChanged("FULLNAME");
					this.OnFULLNAMEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FULLNAME_EN", DbType="VarChar(70)")]
		public string FULLNAME_EN
		{
			get
			{
				return this._FULLNAME_EN;
			}
			set
			{
				if ((this._FULLNAME_EN != value))
				{
					this.OnFULLNAME_ENChanging(value);
					this.SendPropertyChanging();
					this._FULLNAME_EN = value;
					this.SendPropertyChanged("FULLNAME_EN");
					this.OnFULLNAME_ENChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EMAIL", DbType="VarChar(50)")]
		public string EMAIL
		{
			get
			{
				return this._EMAIL;
			}
			set
			{
				if ((this._EMAIL != value))
				{
					this.OnEMAILChanging(value);
					this.SendPropertyChanging();
					this._EMAIL = value;
					this.SendPropertyChanged("EMAIL");
					this.OnEMAILChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NICKNAME", DbType="VarChar(20)")]
		public string NICKNAME
		{
			get
			{
				return this._NICKNAME;
			}
			set
			{
				if ((this._NICKNAME != value))
				{
					this.OnNICKNAMEChanging(value);
					this.SendPropertyChanging();
					this._NICKNAME = value;
					this.SendPropertyChanged("NICKNAME");
					this.OnNICKNAMEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_STARTDATE", DbType="Date")]
		public System.Nullable<System.DateTime> STARTDATE
		{
			get
			{
				return this._STARTDATE;
			}
			set
			{
				if ((this._STARTDATE != value))
				{
					this.OnSTARTDATEChanging(value);
					this.SendPropertyChanging();
					this._STARTDATE = value;
					this.SendPropertyChanged("STARTDATE");
					this.OnSTARTDATEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ENDDATE", DbType="Date")]
		public System.Nullable<System.DateTime> ENDDATE
		{
			get
			{
				return this._ENDDATE;
			}
			set
			{
				if ((this._ENDDATE != value))
				{
					this.OnENDDATEChanging(value);
					this.SendPropertyChanging();
					this._ENDDATE = value;
					this.SendPropertyChanged("ENDDATE");
					this.OnENDDATEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BIRTHDATE", DbType="Date")]
		public System.Nullable<System.DateTime> BIRTHDATE
		{
			get
			{
				return this._BIRTHDATE;
			}
			set
			{
				if ((this._BIRTHDATE != value))
				{
					this.OnBIRTHDATEChanging(value);
					this.SendPropertyChanging();
					this._BIRTHDATE = value;
					this.SendPropertyChanged("BIRTHDATE");
					this.OnBIRTHDATEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FLAG", DbType="Int")]
		public System.Nullable<int> FLAG
		{
			get
			{
				return this._FLAG;
			}
			set
			{
				if ((this._FLAG != value))
				{
					this.OnFLAGChanging(value);
					this.SendPropertyChanging();
					this._FLAG = value;
					this.SendPropertyChanged("FLAG");
					this.OnFLAGChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DELETED", DbType="TinyInt NOT NULL")]
		public byte DELETED
		{
			get
			{
				return this._DELETED;
			}
			set
			{
				if ((this._DELETED != value))
				{
					this.OnDELETEDChanging(value);
					this.SendPropertyChanging();
					this._DELETED = value;
					this.SendPropertyChanged("DELETED");
					this.OnDELETEDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DATECREATE", DbType="Date")]
		public System.Nullable<System.DateTime> DATECREATE
		{
			get
			{
				return this._DATECREATE;
			}
			set
			{
				if ((this._DATECREATE != value))
				{
					this.OnDATECREATEChanging(value);
					this.SendPropertyChanging();
					this._DATECREATE = value;
					this.SendPropertyChanged("DATECREATE");
					this.OnDATECREATEChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.MAS_POSITION")]
	public partial class MAS_POSITION : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _POSITION_ID;
		
		private string _POSITIONE_NAME;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnPOSITION_IDChanging(int value);
    partial void OnPOSITION_IDChanged();
    partial void OnPOSITIONE_NAMEChanging(string value);
    partial void OnPOSITIONE_NAMEChanged();
    #endregion
		
		public MAS_POSITION()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_POSITION_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int POSITION_ID
		{
			get
			{
				return this._POSITION_ID;
			}
			set
			{
				if ((this._POSITION_ID != value))
				{
					this.OnPOSITION_IDChanging(value);
					this.SendPropertyChanging();
					this._POSITION_ID = value;
					this.SendPropertyChanged("POSITION_ID");
					this.OnPOSITION_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_POSITIONE_NAME", DbType="VarChar(50)")]
		public string POSITIONE_NAME
		{
			get
			{
				return this._POSITIONE_NAME;
			}
			set
			{
				if ((this._POSITIONE_NAME != value))
				{
					this.OnPOSITIONE_NAMEChanging(value);
					this.SendPropertyChanging();
					this._POSITIONE_NAME = value;
					this.SendPropertyChanged("POSITIONE_NAME");
					this.OnPOSITIONE_NAMEChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.HR_SALE_USER")]
	public partial class HR_SALE_USER : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _STCODE;
		
		private System.Nullable<decimal> _BAL;
		
		private System.Nullable<decimal> _TOTAL;
		
		private System.Nullable<decimal> _BAL_MAX;
		
		private System.Nullable<int> _STATUS;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnSTCODEChanging(string value);
    partial void OnSTCODEChanged();
    partial void OnBALChanging(System.Nullable<decimal> value);
    partial void OnBALChanged();
    partial void OnTOTALChanging(System.Nullable<decimal> value);
    partial void OnTOTALChanged();
    partial void OnBAL_MAXChanging(System.Nullable<decimal> value);
    partial void OnBAL_MAXChanged();
    partial void OnSTATUSChanging(System.Nullable<int> value);
    partial void OnSTATUSChanged();
    #endregion
		
		public HR_SALE_USER()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_STCODE", DbType="VarChar(5) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string STCODE
		{
			get
			{
				return this._STCODE;
			}
			set
			{
				if ((this._STCODE != value))
				{
					this.OnSTCODEChanging(value);
					this.SendPropertyChanging();
					this._STCODE = value;
					this.SendPropertyChanged("STCODE");
					this.OnSTCODEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BAL", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> BAL
		{
			get
			{
				return this._BAL;
			}
			set
			{
				if ((this._BAL != value))
				{
					this.OnBALChanging(value);
					this.SendPropertyChanging();
					this._BAL = value;
					this.SendPropertyChanged("BAL");
					this.OnBALChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TOTAL", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> TOTAL
		{
			get
			{
				return this._TOTAL;
			}
			set
			{
				if ((this._TOTAL != value))
				{
					this.OnTOTALChanging(value);
					this.SendPropertyChanging();
					this._TOTAL = value;
					this.SendPropertyChanged("TOTAL");
					this.OnTOTALChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BAL_MAX", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> BAL_MAX
		{
			get
			{
				return this._BAL_MAX;
			}
			set
			{
				if ((this._BAL_MAX != value))
				{
					this.OnBAL_MAXChanging(value);
					this.SendPropertyChanging();
					this._BAL_MAX = value;
					this.SendPropertyChanged("BAL_MAX");
					this.OnBAL_MAXChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_STATUS", DbType="Int")]
		public System.Nullable<int> STATUS
		{
			get
			{
				return this._STATUS;
			}
			set
			{
				if ((this._STATUS != value))
				{
					this.OnSTATUSChanging(value);
					this.SendPropertyChanging();
					this._STATUS = value;
					this.SendPropertyChanged("STATUS");
					this.OnSTATUSChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.HR_SALE_PT")]
	public partial class HR_SALE_PT : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _STCODE;
		
		private string _ABBNO;
		
		private System.Nullable<int> _QTY;
		
		private System.Nullable<int> _NET;
		
		private System.Nullable<System.DateTime> _PTTIME;
		
		private System.Nullable<System.DateTime> _WORKDATE;
		
		private System.Nullable<int> _FLAG;
		
		private System.Nullable<int> _ID_ORDER;
		
		private string _DETEIL;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnSTCODEChanging(string value);
    partial void OnSTCODEChanged();
    partial void OnABBNOChanging(string value);
    partial void OnABBNOChanged();
    partial void OnQTYChanging(System.Nullable<int> value);
    partial void OnQTYChanged();
    partial void OnNETChanging(System.Nullable<int> value);
    partial void OnNETChanged();
    partial void OnPTTIMEChanging(System.Nullable<System.DateTime> value);
    partial void OnPTTIMEChanged();
    partial void OnWORKDATEChanging(System.Nullable<System.DateTime> value);
    partial void OnWORKDATEChanged();
    partial void OnFLAGChanging(System.Nullable<int> value);
    partial void OnFLAGChanged();
    partial void OnID_ORDERChanging(System.Nullable<int> value);
    partial void OnID_ORDERChanged();
    partial void OnDETEILChanging(string value);
    partial void OnDETEILChanged();
    #endregion
		
		public HR_SALE_PT()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_STCODE", DbType="VarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string STCODE
		{
			get
			{
				return this._STCODE;
			}
			set
			{
				if ((this._STCODE != value))
				{
					this.OnSTCODEChanging(value);
					this.SendPropertyChanging();
					this._STCODE = value;
					this.SendPropertyChanged("STCODE");
					this.OnSTCODEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ABBNO", DbType="VarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string ABBNO
		{
			get
			{
				return this._ABBNO;
			}
			set
			{
				if ((this._ABBNO != value))
				{
					this.OnABBNOChanging(value);
					this.SendPropertyChanging();
					this._ABBNO = value;
					this.SendPropertyChanged("ABBNO");
					this.OnABBNOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_QTY", DbType="Int")]
		public System.Nullable<int> QTY
		{
			get
			{
				return this._QTY;
			}
			set
			{
				if ((this._QTY != value))
				{
					this.OnQTYChanging(value);
					this.SendPropertyChanging();
					this._QTY = value;
					this.SendPropertyChanged("QTY");
					this.OnQTYChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NET", DbType="Int")]
		public System.Nullable<int> NET
		{
			get
			{
				return this._NET;
			}
			set
			{
				if ((this._NET != value))
				{
					this.OnNETChanging(value);
					this.SendPropertyChanging();
					this._NET = value;
					this.SendPropertyChanged("NET");
					this.OnNETChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PTTIME", DbType="DateTime")]
		public System.Nullable<System.DateTime> PTTIME
		{
			get
			{
				return this._PTTIME;
			}
			set
			{
				if ((this._PTTIME != value))
				{
					this.OnPTTIMEChanging(value);
					this.SendPropertyChanging();
					this._PTTIME = value;
					this.SendPropertyChanged("PTTIME");
					this.OnPTTIMEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_WORKDATE", DbType="DateTime")]
		public System.Nullable<System.DateTime> WORKDATE
		{
			get
			{
				return this._WORKDATE;
			}
			set
			{
				if ((this._WORKDATE != value))
				{
					this.OnWORKDATEChanging(value);
					this.SendPropertyChanging();
					this._WORKDATE = value;
					this.SendPropertyChanged("WORKDATE");
					this.OnWORKDATEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FLAG", DbType="Int")]
		public System.Nullable<int> FLAG
		{
			get
			{
				return this._FLAG;
			}
			set
			{
				if ((this._FLAG != value))
				{
					this.OnFLAGChanging(value);
					this.SendPropertyChanging();
					this._FLAG = value;
					this.SendPropertyChanged("FLAG");
					this.OnFLAGChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_ORDER", DbType="Int")]
		public System.Nullable<int> ID_ORDER
		{
			get
			{
				return this._ID_ORDER;
			}
			set
			{
				if ((this._ID_ORDER != value))
				{
					this.OnID_ORDERChanging(value);
					this.SendPropertyChanging();
					this._ID_ORDER = value;
					this.SendPropertyChanged("ID_ORDER");
					this.OnID_ORDERChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DETEIL", DbType="VarChar(MAX)")]
		public string DETEIL
		{
			get
			{
				return this._DETEIL;
			}
			set
			{
				if ((this._DETEIL != value))
				{
					this.OnDETEILChanging(value);
					this.SendPropertyChanging();
					this._DETEIL = value;
					this.SendPropertyChanged("DETEIL");
					this.OnDETEILChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.HR_SALE_PI")]
	public partial class HR_SALE_PI : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _STCODE;
		
		private string _ABBNO;
		
		private string _MPCODE;
		
		private System.Nullable<int> _QTY;
		
		private System.Nullable<int> _PRICE;
		
		private System.Nullable<int> _NET;
		
		private System.Nullable<System.DateTime> _PTDATE;
		
		private System.Nullable<System.DateTime> _WORKDATE;
		
		private System.Nullable<int> _FLAG;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnSTCODEChanging(string value);
    partial void OnSTCODEChanged();
    partial void OnABBNOChanging(string value);
    partial void OnABBNOChanged();
    partial void OnMPCODEChanging(string value);
    partial void OnMPCODEChanged();
    partial void OnQTYChanging(System.Nullable<int> value);
    partial void OnQTYChanged();
    partial void OnPRICEChanging(System.Nullable<int> value);
    partial void OnPRICEChanged();
    partial void OnNETChanging(System.Nullable<int> value);
    partial void OnNETChanged();
    partial void OnPTDATEChanging(System.Nullable<System.DateTime> value);
    partial void OnPTDATEChanged();
    partial void OnWORKDATEChanging(System.Nullable<System.DateTime> value);
    partial void OnWORKDATEChanged();
    partial void OnFLAGChanging(System.Nullable<int> value);
    partial void OnFLAGChanged();
    #endregion
		
		public HR_SALE_PI()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_STCODE", DbType="VarChar(5) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string STCODE
		{
			get
			{
				return this._STCODE;
			}
			set
			{
				if ((this._STCODE != value))
				{
					this.OnSTCODEChanging(value);
					this.SendPropertyChanging();
					this._STCODE = value;
					this.SendPropertyChanged("STCODE");
					this.OnSTCODEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ABBNO", DbType="VarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string ABBNO
		{
			get
			{
				return this._ABBNO;
			}
			set
			{
				if ((this._ABBNO != value))
				{
					this.OnABBNOChanging(value);
					this.SendPropertyChanging();
					this._ABBNO = value;
					this.SendPropertyChanged("ABBNO");
					this.OnABBNOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MPCODE", DbType="VarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MPCODE
		{
			get
			{
				return this._MPCODE;
			}
			set
			{
				if ((this._MPCODE != value))
				{
					this.OnMPCODEChanging(value);
					this.SendPropertyChanging();
					this._MPCODE = value;
					this.SendPropertyChanged("MPCODE");
					this.OnMPCODEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_QTY", DbType="Int")]
		public System.Nullable<int> QTY
		{
			get
			{
				return this._QTY;
			}
			set
			{
				if ((this._QTY != value))
				{
					this.OnQTYChanging(value);
					this.SendPropertyChanging();
					this._QTY = value;
					this.SendPropertyChanged("QTY");
					this.OnQTYChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PRICE", DbType="Int")]
		public System.Nullable<int> PRICE
		{
			get
			{
				return this._PRICE;
			}
			set
			{
				if ((this._PRICE != value))
				{
					this.OnPRICEChanging(value);
					this.SendPropertyChanging();
					this._PRICE = value;
					this.SendPropertyChanged("PRICE");
					this.OnPRICEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NET", DbType="Int")]
		public System.Nullable<int> NET
		{
			get
			{
				return this._NET;
			}
			set
			{
				if ((this._NET != value))
				{
					this.OnNETChanging(value);
					this.SendPropertyChanging();
					this._NET = value;
					this.SendPropertyChanged("NET");
					this.OnNETChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PTDATE", DbType="DateTime")]
		public System.Nullable<System.DateTime> PTDATE
		{
			get
			{
				return this._PTDATE;
			}
			set
			{
				if ((this._PTDATE != value))
				{
					this.OnPTDATEChanging(value);
					this.SendPropertyChanging();
					this._PTDATE = value;
					this.SendPropertyChanged("PTDATE");
					this.OnPTDATEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_WORKDATE", DbType="DateTime")]
		public System.Nullable<System.DateTime> WORKDATE
		{
			get
			{
				return this._WORKDATE;
			}
			set
			{
				if ((this._WORKDATE != value))
				{
					this.OnWORKDATEChanging(value);
					this.SendPropertyChanging();
					this._WORKDATE = value;
					this.SendPropertyChanged("WORKDATE");
					this.OnWORKDATEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FLAG", DbType="Int")]
		public System.Nullable<int> FLAG
		{
			get
			{
				return this._FLAG;
			}
			set
			{
				if ((this._FLAG != value))
				{
					this.OnFLAGChanging(value);
					this.SendPropertyChanging();
					this._FLAG = value;
					this.SendPropertyChanged("FLAG");
					this.OnFLAGChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.HR_LVL")]
	public partial class HR_LVL : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID_LVL;
		
		private string _LVL;
		
		private string _SECTION;
		
		private System.Nullable<decimal> _CBAL;
		
		private System.Nullable<decimal> _BAL;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnID_LVLChanging(int value);
    partial void OnID_LVLChanged();
    partial void OnLVLChanging(string value);
    partial void OnLVLChanged();
    partial void OnSECTIONChanging(string value);
    partial void OnSECTIONChanged();
    partial void OnCBALChanging(System.Nullable<decimal> value);
    partial void OnCBALChanged();
    partial void OnBALChanging(System.Nullable<decimal> value);
    partial void OnBALChanged();
    #endregion
		
		public HR_LVL()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_LVL", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int ID_LVL
		{
			get
			{
				return this._ID_LVL;
			}
			set
			{
				if ((this._ID_LVL != value))
				{
					this.OnID_LVLChanging(value);
					this.SendPropertyChanging();
					this._ID_LVL = value;
					this.SendPropertyChanged("ID_LVL");
					this.OnID_LVLChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LVL", DbType="VarChar(10)")]
		public string LVL
		{
			get
			{
				return this._LVL;
			}
			set
			{
				if ((this._LVL != value))
				{
					this.OnLVLChanging(value);
					this.SendPropertyChanging();
					this._LVL = value;
					this.SendPropertyChanged("LVL");
					this.OnLVLChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SECTION", DbType="VarChar(20)")]
		public string SECTION
		{
			get
			{
				return this._SECTION;
			}
			set
			{
				if ((this._SECTION != value))
				{
					this.OnSECTIONChanging(value);
					this.SendPropertyChanging();
					this._SECTION = value;
					this.SendPropertyChanged("SECTION");
					this.OnSECTIONChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CBAL", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> CBAL
		{
			get
			{
				return this._CBAL;
			}
			set
			{
				if ((this._CBAL != value))
				{
					this.OnCBALChanging(value);
					this.SendPropertyChanging();
					this._CBAL = value;
					this.SendPropertyChanged("CBAL");
					this.OnCBALChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BAL", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> BAL
		{
			get
			{
				return this._BAL;
			}
			set
			{
				if ((this._BAL != value))
				{
					this.OnBALChanging(value);
					this.SendPropertyChanging();
					this._BAL = value;
					this.SendPropertyChanged("BAL");
					this.OnBALChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.VW_DEP")]
	public partial class VW_DEP
	{
		
		private string _DPCODE;
		
		public VW_DEP()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DPCODE", DbType="VarChar(10)")]
		public string DPCODE
		{
			get
			{
				return this._DPCODE;
			}
			set
			{
				if ((this._DPCODE != value))
				{
					this._DPCODE = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.VW_USER_PRO")]
	public partial class VW_USER_PRO
	{
		
		private string _STCODE;
		
		private string _DEGREE;
		
		private string _DPCODE;
		
		private string _DPNAME;
		
		private string _FULLNAME;
		
		private string _NICKNAME;
		
		private string _ENDDATE;
		
		public VW_USER_PRO()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_STCODE", DbType="VarChar(5) NOT NULL", CanBeNull=false)]
		public string STCODE
		{
			get
			{
				return this._STCODE;
			}
			set
			{
				if ((this._STCODE != value))
				{
					this._STCODE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DEGREE", DbType="VarChar(10)")]
		public string DEGREE
		{
			get
			{
				return this._DEGREE;
			}
			set
			{
				if ((this._DEGREE != value))
				{
					this._DEGREE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DPCODE", DbType="VarChar(10)")]
		public string DPCODE
		{
			get
			{
				return this._DPCODE;
			}
			set
			{
				if ((this._DPCODE != value))
				{
					this._DPCODE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DPNAME", DbType="VarChar(70)")]
		public string DPNAME
		{
			get
			{
				return this._DPNAME;
			}
			set
			{
				if ((this._DPNAME != value))
				{
					this._DPNAME = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FULLNAME", DbType="VarChar(70)")]
		public string FULLNAME
		{
			get
			{
				return this._FULLNAME;
			}
			set
			{
				if ((this._FULLNAME != value))
				{
					this._FULLNAME = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NICKNAME", DbType="VarChar(20)")]
		public string NICKNAME
		{
			get
			{
				return this._NICKNAME;
			}
			set
			{
				if ((this._NICKNAME != value))
				{
					this._NICKNAME = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ENDDATE", DbType="VarChar(30)")]
		public string ENDDATE
		{
			get
			{
				return this._ENDDATE;
			}
			set
			{
				if ((this._ENDDATE != value))
				{
					this._ENDDATE = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.VW_SHOW_PRODUCT")]
	public partial class VW_SHOW_PRODUCT
	{
		
		private string _CPRICE;
		
		private string _UserName;
		
		private string _STCODE;
		
		private string _ABBNO;
		
		private string _Expr1;
		
		private System.Nullable<int> _QTY;
		
		private System.Nullable<int> _NET;
		
		private System.Nullable<System.DateTime> _PTDATE;
		
		private string _CDATE;
		
		private System.Nullable<int> _FLAG;
		
		private string _MPCODE;
		
		private string _MPNAME;
		
		private string _SPRICE;
		
		public VW_SHOW_PRODUCT()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CPRICE", DbType="VarChar(30)")]
		public string CPRICE
		{
			get
			{
				return this._CPRICE;
			}
			set
			{
				if ((this._CPRICE != value))
				{
					this._CPRICE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserName", DbType="VarChar(60)")]
		public string UserName
		{
			get
			{
				return this._UserName;
			}
			set
			{
				if ((this._UserName != value))
				{
					this._UserName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_STCODE", DbType="VarChar(5) NOT NULL", CanBeNull=false)]
		public string STCODE
		{
			get
			{
				return this._STCODE;
			}
			set
			{
				if ((this._STCODE != value))
				{
					this._STCODE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ABBNO", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string ABBNO
		{
			get
			{
				return this._ABBNO;
			}
			set
			{
				if ((this._ABBNO != value))
				{
					this._ABBNO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Expr1", DbType="VarChar(5) NOT NULL", CanBeNull=false)]
		public string Expr1
		{
			get
			{
				return this._Expr1;
			}
			set
			{
				if ((this._Expr1 != value))
				{
					this._Expr1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_QTY", DbType="Int")]
		public System.Nullable<int> QTY
		{
			get
			{
				return this._QTY;
			}
			set
			{
				if ((this._QTY != value))
				{
					this._QTY = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NET", DbType="Int")]
		public System.Nullable<int> NET
		{
			get
			{
				return this._NET;
			}
			set
			{
				if ((this._NET != value))
				{
					this._NET = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PTDATE", DbType="DateTime")]
		public System.Nullable<System.DateTime> PTDATE
		{
			get
			{
				return this._PTDATE;
			}
			set
			{
				if ((this._PTDATE != value))
				{
					this._PTDATE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CDATE", DbType="VarChar(30)")]
		public string CDATE
		{
			get
			{
				return this._CDATE;
			}
			set
			{
				if ((this._CDATE != value))
				{
					this._CDATE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FLAG", DbType="Int")]
		public System.Nullable<int> FLAG
		{
			get
			{
				return this._FLAG;
			}
			set
			{
				if ((this._FLAG != value))
				{
					this._FLAG = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MPCODE", DbType="VarChar(15)")]
		public string MPCODE
		{
			get
			{
				return this._MPCODE;
			}
			set
			{
				if ((this._MPCODE != value))
				{
					this._MPCODE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MPNAME", DbType="VarChar(60)")]
		public string MPNAME
		{
			get
			{
				return this._MPNAME;
			}
			set
			{
				if ((this._MPNAME != value))
				{
					this._MPNAME = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SPRICE", DbType="VarChar(30)")]
		public string SPRICE
		{
			get
			{
				return this._SPRICE;
			}
			set
			{
				if ((this._SPRICE != value))
				{
					this._SPRICE = value;
				}
			}
		}
	}
	
	public partial class HR_SALE_GetALLManagementResult
	{
		
		private string _MPCODE;
		
		private string _ABBNAME;
		
		private System.Nullable<int> _SUM;
		
		public HR_SALE_GetALLManagementResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MPCODE", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string MPCODE
		{
			get
			{
				return this._MPCODE;
			}
			set
			{
				if ((this._MPCODE != value))
				{
					this._MPCODE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ABBNAME", DbType="VarChar(18)")]
		public string ABBNAME
		{
			get
			{
				return this._ABBNAME;
			}
			set
			{
				if ((this._ABBNAME != value))
				{
					this._ABBNAME = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SUM", DbType="Int")]
		public System.Nullable<int> SUM
		{
			get
			{
				return this._SUM;
			}
			set
			{
				if ((this._SUM != value))
				{
					this._SUM = value;
				}
			}
		}
	}
	
	public partial class HR_SALE_GetBalResult
	{
		
		private System.Nullable<decimal> _Total;
		
		private System.Nullable<int> _NET;
		
		public HR_SALE_GetBalResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Total", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> Total
		{
			get
			{
				return this._Total;
			}
			set
			{
				if ((this._Total != value))
				{
					this._Total = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NET", DbType="Int")]
		public System.Nullable<int> NET
		{
			get
			{
				return this._NET;
			}
			set
			{
				if ((this._NET != value))
				{
					this._NET = value;
				}
			}
		}
	}
	
	public partial class HR_SALE_GetManagementResult
	{
		
		private string _DPCODE;
		
		private string _FULLNAME;
		
		private string _STCODE;
		
		private string _ABBNO;
		
		private System.Nullable<int> _QTY;
		
		private string _NET;
		
		private string _PTDATE;
		
		private System.Nullable<int> _FLAG;
		
		private System.Nullable<int> _ID_ORDER;
		
		public HR_SALE_GetManagementResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DPCODE", DbType="VarChar(10)")]
		public string DPCODE
		{
			get
			{
				return this._DPCODE;
			}
			set
			{
				if ((this._DPCODE != value))
				{
					this._DPCODE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FULLNAME", DbType="VarChar(70)")]
		public string FULLNAME
		{
			get
			{
				return this._FULLNAME;
			}
			set
			{
				if ((this._FULLNAME != value))
				{
					this._FULLNAME = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_STCODE", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string STCODE
		{
			get
			{
				return this._STCODE;
			}
			set
			{
				if ((this._STCODE != value))
				{
					this._STCODE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ABBNO", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string ABBNO
		{
			get
			{
				return this._ABBNO;
			}
			set
			{
				if ((this._ABBNO != value))
				{
					this._ABBNO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_QTY", DbType="Int")]
		public System.Nullable<int> QTY
		{
			get
			{
				return this._QTY;
			}
			set
			{
				if ((this._QTY != value))
				{
					this._QTY = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NET", DbType="VarChar(30)")]
		public string NET
		{
			get
			{
				return this._NET;
			}
			set
			{
				if ((this._NET != value))
				{
					this._NET = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PTDATE", DbType="VarChar(30)")]
		public string PTDATE
		{
			get
			{
				return this._PTDATE;
			}
			set
			{
				if ((this._PTDATE != value))
				{
					this._PTDATE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FLAG", DbType="Int")]
		public System.Nullable<int> FLAG
		{
			get
			{
				return this._FLAG;
			}
			set
			{
				if ((this._FLAG != value))
				{
					this._FLAG = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_ORDER", DbType="Int")]
		public System.Nullable<int> ID_ORDER
		{
			get
			{
				return this._ID_ORDER;
			}
			set
			{
				if ((this._ID_ORDER != value))
				{
					this._ID_ORDER = value;
				}
			}
		}
	}
	
	public partial class HR_SALE_GETUSERResult
	{
		
		private string _STCODE;
		
		private System.Nullable<decimal> _BAL;
		
		private System.Nullable<decimal> _TOTAL;
		
		private System.Nullable<decimal> _BAL_MAX;
		
		private System.Nullable<int> _STATUS;
		
		private string _CTotal;
		
		private string _CBal;
		
		private string _ABal;
		
		public HR_SALE_GETUSERResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_STCODE", DbType="VarChar(5) NOT NULL", CanBeNull=false)]
		public string STCODE
		{
			get
			{
				return this._STCODE;
			}
			set
			{
				if ((this._STCODE != value))
				{
					this._STCODE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BAL", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> BAL
		{
			get
			{
				return this._BAL;
			}
			set
			{
				if ((this._BAL != value))
				{
					this._BAL = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TOTAL", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> TOTAL
		{
			get
			{
				return this._TOTAL;
			}
			set
			{
				if ((this._TOTAL != value))
				{
					this._TOTAL = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BAL_MAX", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> BAL_MAX
		{
			get
			{
				return this._BAL_MAX;
			}
			set
			{
				if ((this._BAL_MAX != value))
				{
					this._BAL_MAX = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_STATUS", DbType="Int")]
		public System.Nullable<int> STATUS
		{
			get
			{
				return this._STATUS;
			}
			set
			{
				if ((this._STATUS != value))
				{
					this._STATUS = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CTotal", DbType="VarChar(30)")]
		public string CTotal
		{
			get
			{
				return this._CTotal;
			}
			set
			{
				if ((this._CTotal != value))
				{
					this._CTotal = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CBal", DbType="VarChar(30)")]
		public string CBal
		{
			get
			{
				return this._CBal;
			}
			set
			{
				if ((this._CBal != value))
				{
					this._CBal = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ABal", DbType="VarChar(30)")]
		public string ABal
		{
			get
			{
				return this._ABal;
			}
			set
			{
				if ((this._ABal != value))
				{
					this._ABal = value;
				}
			}
		}
	}
	
	public partial class HR_SALE_ShowHistoryResult
	{
		
		private string _STCODE;
		
		private string _ABBNO;
		
		private System.Nullable<int> _QTY;
		
		private string _NET;
		
		private string _WORKDATE;
		
		private System.Nullable<int> _FLAG;
		
		private System.Nullable<int> _ID_ORDER;
		
		private string _DETEIL;
		
		public HR_SALE_ShowHistoryResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_STCODE", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string STCODE
		{
			get
			{
				return this._STCODE;
			}
			set
			{
				if ((this._STCODE != value))
				{
					this._STCODE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ABBNO", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string ABBNO
		{
			get
			{
				return this._ABBNO;
			}
			set
			{
				if ((this._ABBNO != value))
				{
					this._ABBNO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_QTY", DbType="Int")]
		public System.Nullable<int> QTY
		{
			get
			{
				return this._QTY;
			}
			set
			{
				if ((this._QTY != value))
				{
					this._QTY = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NET", DbType="VarChar(30)")]
		public string NET
		{
			get
			{
				return this._NET;
			}
			set
			{
				if ((this._NET != value))
				{
					this._NET = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_WORKDATE", DbType="VarChar(30)")]
		public string WORKDATE
		{
			get
			{
				return this._WORKDATE;
			}
			set
			{
				if ((this._WORKDATE != value))
				{
					this._WORKDATE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FLAG", DbType="Int")]
		public System.Nullable<int> FLAG
		{
			get
			{
				return this._FLAG;
			}
			set
			{
				if ((this._FLAG != value))
				{
					this._FLAG = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_ORDER", DbType="Int")]
		public System.Nullable<int> ID_ORDER
		{
			get
			{
				return this._ID_ORDER;
			}
			set
			{
				if ((this._ID_ORDER != value))
				{
					this._ID_ORDER = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DETEIL", DbType="VarChar(MAX)")]
		public string DETEIL
		{
			get
			{
				return this._DETEIL;
			}
			set
			{
				if ((this._DETEIL != value))
				{
					this._DETEIL = value;
				}
			}
		}
	}
	
	public partial class HR_SALE_ShowPIResult
	{
		
		private string _MPCODE;
		
		private string _FULLNAME;
		
		private System.Nullable<int> _QTY;
		
		private string _DETEIL;
		
		private System.Nullable<long> _Row_;
		
		public HR_SALE_ShowPIResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MPCODE", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string MPCODE
		{
			get
			{
				return this._MPCODE;
			}
			set
			{
				if ((this._MPCODE != value))
				{
					this._MPCODE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FULLNAME", DbType="VarChar(60)")]
		public string FULLNAME
		{
			get
			{
				return this._FULLNAME;
			}
			set
			{
				if ((this._FULLNAME != value))
				{
					this._FULLNAME = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_QTY", DbType="Int")]
		public System.Nullable<int> QTY
		{
			get
			{
				return this._QTY;
			}
			set
			{
				if ((this._QTY != value))
				{
					this._QTY = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DETEIL", DbType="VarChar(MAX)")]
		public string DETEIL
		{
			get
			{
				return this._DETEIL;
			}
			set
			{
				if ((this._DETEIL != value))
				{
					this._DETEIL = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="Row#", Storage="_Row_", DbType="BigInt")]
		public System.Nullable<long> Row_
		{
			get
			{
				return this._Row_;
			}
			set
			{
				if ((this._Row_ != value))
				{
					this._Row_ = value;
				}
			}
		}
	}
	
	public partial class HR_SALE_POSResult
	{
		
		private string _STCODE;
		
		private string _ABBNO;
		
		private System.Nullable<System.DateTime> _WORKDATE;
		
		private System.Nullable<int> _ID_ORDER;
		
		private string _MPCODE;
		
		private System.Nullable<int> _QTY;
		
		private System.Nullable<int> _PRICE;
		
		private System.Nullable<int> _NET;
		
		public HR_SALE_POSResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_STCODE", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string STCODE
		{
			get
			{
				return this._STCODE;
			}
			set
			{
				if ((this._STCODE != value))
				{
					this._STCODE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ABBNO", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string ABBNO
		{
			get
			{
				return this._ABBNO;
			}
			set
			{
				if ((this._ABBNO != value))
				{
					this._ABBNO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_WORKDATE", DbType="DateTime")]
		public System.Nullable<System.DateTime> WORKDATE
		{
			get
			{
				return this._WORKDATE;
			}
			set
			{
				if ((this._WORKDATE != value))
				{
					this._WORKDATE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_ORDER", DbType="Int")]
		public System.Nullable<int> ID_ORDER
		{
			get
			{
				return this._ID_ORDER;
			}
			set
			{
				if ((this._ID_ORDER != value))
				{
					this._ID_ORDER = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MPCODE", DbType="VarChar(50)")]
		public string MPCODE
		{
			get
			{
				return this._MPCODE;
			}
			set
			{
				if ((this._MPCODE != value))
				{
					this._MPCODE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_QTY", DbType="Int")]
		public System.Nullable<int> QTY
		{
			get
			{
				return this._QTY;
			}
			set
			{
				if ((this._QTY != value))
				{
					this._QTY = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PRICE", DbType="Int")]
		public System.Nullable<int> PRICE
		{
			get
			{
				return this._PRICE;
			}
			set
			{
				if ((this._PRICE != value))
				{
					this._PRICE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NET", DbType="Int")]
		public System.Nullable<int> NET
		{
			get
			{
				return this._NET;
			}
			set
			{
				if ((this._NET != value))
				{
					this._NET = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
