#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAPI.DATA.HR_SALE
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="MONA110601")]
	public partial class Mona77DataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    #endregion
		
		public Mona77DataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["MONA110601ConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public Mona77DataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public Mona77DataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public Mona77DataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public Mona77DataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.PP_GET_HR_MP")]
		public ISingleResult<PP_GET_HR_MPResult> PP_GET_HR_MP([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(20)")] string seach)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), seach);
			return ((ISingleResult<PP_GET_HR_MPResult>)(result.ReturnValue));
		}
	}
	
	public partial class PP_GET_HR_MPResult
	{
		
		private string _DIMENSION1;
		
		private string _CODE;
		
		private string _NAMETH;
		
		private string _PRICE;
		
		private string _MAXPRICE;
		
		public PP_GET_HR_MPResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DIMENSION1", DbType="VarChar(35)")]
		public string DIMENSION1
		{
			get
			{
				return this._DIMENSION1;
			}
			set
			{
				if ((this._DIMENSION1 != value))
				{
					this._DIMENSION1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CODE", DbType="VarChar(35) NOT NULL", CanBeNull=false)]
		public string CODE
		{
			get
			{
				return this._CODE;
			}
			set
			{
				if ((this._CODE != value))
				{
					this._CODE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NAMETH", DbType="VarChar(255) NOT NULL", CanBeNull=false)]
		public string NAMETH
		{
			get
			{
				return this._NAMETH;
			}
			set
			{
				if ((this._NAMETH != value))
				{
					this._NAMETH = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PRICE", DbType="VarChar(30)")]
		public string PRICE
		{
			get
			{
				return this._PRICE;
			}
			set
			{
				if ((this._PRICE != value))
				{
					this._PRICE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MAXPRICE", DbType="VarChar(30)")]
		public string MAXPRICE
		{
			get
			{
				return this._MAXPRICE;
			}
			set
			{
				if ((this._MAXPRICE != value))
				{
					this._MAXPRICE = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
