#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAPI.DATA.dbMasIT
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="dbMasIT")]
	public partial class LoginMainDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertMAS_USER_SYSTEM(MAS_USER_SYSTEM instance);
    partial void UpdateMAS_USER_SYSTEM(MAS_USER_SYSTEM instance);
    partial void DeleteMAS_USER_SYSTEM(MAS_USER_SYSTEM instance);
    #endregion
		
		public LoginMainDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["dbMasITConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public LoginMainDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public LoginMainDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public LoginMainDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public LoginMainDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<MAS_USER_SYSTEM> MAS_USER_SYSTEMs
		{
			get
			{
				return this.GetTable<MAS_USER_SYSTEM>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.MAS_USER_SYSTEM")]
	public partial class MAS_USER_SYSTEM : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _STCODE;
		
		private string _PASS;
		
		private string _POSITION;
		
		private string _DEGREE;
		
		private string _DPCODE;
		
		private string _DPNAME;
		
		private string _FULLNAME;
		
		private string _FULLNAME_EN;
		
		private string _EMAIL;
		
		private string _NICKNAME;
		
		private System.Nullable<System.DateTime> _STARTDATE;
		
		private System.Nullable<System.DateTime> _ENDDATE;
		
		private System.Nullable<System.DateTime> _BIRTHDATE;
		
		private System.Nullable<int> _FLAG;
		
		private byte _DELETED;
		
		private System.Nullable<System.DateTime> _DATECREATE;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnSTCODEChanging(string value);
    partial void OnSTCODEChanged();
    partial void OnPASSChanging(string value);
    partial void OnPASSChanged();
    partial void OnPOSITIONChanging(string value);
    partial void OnPOSITIONChanged();
    partial void OnDEGREEChanging(string value);
    partial void OnDEGREEChanged();
    partial void OnDPCODEChanging(string value);
    partial void OnDPCODEChanged();
    partial void OnDPNAMEChanging(string value);
    partial void OnDPNAMEChanged();
    partial void OnFULLNAMEChanging(string value);
    partial void OnFULLNAMEChanged();
    partial void OnFULLNAME_ENChanging(string value);
    partial void OnFULLNAME_ENChanged();
    partial void OnEMAILChanging(string value);
    partial void OnEMAILChanged();
    partial void OnNICKNAMEChanging(string value);
    partial void OnNICKNAMEChanged();
    partial void OnSTARTDATEChanging(System.Nullable<System.DateTime> value);
    partial void OnSTARTDATEChanged();
    partial void OnENDDATEChanging(System.Nullable<System.DateTime> value);
    partial void OnENDDATEChanged();
    partial void OnBIRTHDATEChanging(System.Nullable<System.DateTime> value);
    partial void OnBIRTHDATEChanged();
    partial void OnFLAGChanging(System.Nullable<int> value);
    partial void OnFLAGChanged();
    partial void OnDELETEDChanging(byte value);
    partial void OnDELETEDChanged();
    partial void OnDATECREATEChanging(System.Nullable<System.DateTime> value);
    partial void OnDATECREATEChanged();
    #endregion
		
		public MAS_USER_SYSTEM()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_STCODE", DbType="VarChar(5) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string STCODE
		{
			get
			{
				return this._STCODE;
			}
			set
			{
				if ((this._STCODE != value))
				{
					this.OnSTCODEChanging(value);
					this.SendPropertyChanging();
					this._STCODE = value;
					this.SendPropertyChanged("STCODE");
					this.OnSTCODEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PASS", DbType="VarChar(20)")]
		public string PASS
		{
			get
			{
				return this._PASS;
			}
			set
			{
				if ((this._PASS != value))
				{
					this.OnPASSChanging(value);
					this.SendPropertyChanging();
					this._PASS = value;
					this.SendPropertyChanged("PASS");
					this.OnPASSChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_POSITION", DbType="VarChar(25)")]
		public string POSITION
		{
			get
			{
				return this._POSITION;
			}
			set
			{
				if ((this._POSITION != value))
				{
					this.OnPOSITIONChanging(value);
					this.SendPropertyChanging();
					this._POSITION = value;
					this.SendPropertyChanged("POSITION");
					this.OnPOSITIONChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DEGREE", DbType="VarChar(10)")]
		public string DEGREE
		{
			get
			{
				return this._DEGREE;
			}
			set
			{
				if ((this._DEGREE != value))
				{
					this.OnDEGREEChanging(value);
					this.SendPropertyChanging();
					this._DEGREE = value;
					this.SendPropertyChanged("DEGREE");
					this.OnDEGREEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DPCODE", DbType="VarChar(10)")]
		public string DPCODE
		{
			get
			{
				return this._DPCODE;
			}
			set
			{
				if ((this._DPCODE != value))
				{
					this.OnDPCODEChanging(value);
					this.SendPropertyChanging();
					this._DPCODE = value;
					this.SendPropertyChanged("DPCODE");
					this.OnDPCODEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DPNAME", DbType="VarChar(70)")]
		public string DPNAME
		{
			get
			{
				return this._DPNAME;
			}
			set
			{
				if ((this._DPNAME != value))
				{
					this.OnDPNAMEChanging(value);
					this.SendPropertyChanging();
					this._DPNAME = value;
					this.SendPropertyChanged("DPNAME");
					this.OnDPNAMEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FULLNAME", DbType="VarChar(70)")]
		public string FULLNAME
		{
			get
			{
				return this._FULLNAME;
			}
			set
			{
				if ((this._FULLNAME != value))
				{
					this.OnFULLNAMEChanging(value);
					this.SendPropertyChanging();
					this._FULLNAME = value;
					this.SendPropertyChanged("FULLNAME");
					this.OnFULLNAMEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FULLNAME_EN", DbType="VarChar(70)")]
		public string FULLNAME_EN
		{
			get
			{
				return this._FULLNAME_EN;
			}
			set
			{
				if ((this._FULLNAME_EN != value))
				{
					this.OnFULLNAME_ENChanging(value);
					this.SendPropertyChanging();
					this._FULLNAME_EN = value;
					this.SendPropertyChanged("FULLNAME_EN");
					this.OnFULLNAME_ENChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EMAIL", DbType="VarChar(50)")]
		public string EMAIL
		{
			get
			{
				return this._EMAIL;
			}
			set
			{
				if ((this._EMAIL != value))
				{
					this.OnEMAILChanging(value);
					this.SendPropertyChanging();
					this._EMAIL = value;
					this.SendPropertyChanged("EMAIL");
					this.OnEMAILChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NICKNAME", DbType="VarChar(20)")]
		public string NICKNAME
		{
			get
			{
				return this._NICKNAME;
			}
			set
			{
				if ((this._NICKNAME != value))
				{
					this.OnNICKNAMEChanging(value);
					this.SendPropertyChanging();
					this._NICKNAME = value;
					this.SendPropertyChanged("NICKNAME");
					this.OnNICKNAMEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_STARTDATE", DbType="Date")]
		public System.Nullable<System.DateTime> STARTDATE
		{
			get
			{
				return this._STARTDATE;
			}
			set
			{
				if ((this._STARTDATE != value))
				{
					this.OnSTARTDATEChanging(value);
					this.SendPropertyChanging();
					this._STARTDATE = value;
					this.SendPropertyChanged("STARTDATE");
					this.OnSTARTDATEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ENDDATE", DbType="Date")]
		public System.Nullable<System.DateTime> ENDDATE
		{
			get
			{
				return this._ENDDATE;
			}
			set
			{
				if ((this._ENDDATE != value))
				{
					this.OnENDDATEChanging(value);
					this.SendPropertyChanging();
					this._ENDDATE = value;
					this.SendPropertyChanged("ENDDATE");
					this.OnENDDATEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BIRTHDATE", DbType="Date")]
		public System.Nullable<System.DateTime> BIRTHDATE
		{
			get
			{
				return this._BIRTHDATE;
			}
			set
			{
				if ((this._BIRTHDATE != value))
				{
					this.OnBIRTHDATEChanging(value);
					this.SendPropertyChanging();
					this._BIRTHDATE = value;
					this.SendPropertyChanged("BIRTHDATE");
					this.OnBIRTHDATEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FLAG", DbType="Int")]
		public System.Nullable<int> FLAG
		{
			get
			{
				return this._FLAG;
			}
			set
			{
				if ((this._FLAG != value))
				{
					this.OnFLAGChanging(value);
					this.SendPropertyChanging();
					this._FLAG = value;
					this.SendPropertyChanged("FLAG");
					this.OnFLAGChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DELETED", DbType="TinyInt NOT NULL")]
		public byte DELETED
		{
			get
			{
				return this._DELETED;
			}
			set
			{
				if ((this._DELETED != value))
				{
					this.OnDELETEDChanging(value);
					this.SendPropertyChanging();
					this._DELETED = value;
					this.SendPropertyChanged("DELETED");
					this.OnDELETEDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DATECREATE", DbType="Date")]
		public System.Nullable<System.DateTime> DATECREATE
		{
			get
			{
				return this._DATECREATE;
			}
			set
			{
				if ((this._DATECREATE != value))
				{
					this.OnDATECREATEChanging(value);
					this.SendPropertyChanging();
					this._DATECREATE = value;
					this.SendPropertyChanged("DATECREATE");
					this.OnDATECREATEChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
